### ISSUE TITLE
CentOs 6 package installs wrong version of oxd server 2.4.4 instead of 3.1.1

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#105]
Followed the instructions at [https://gluu.org/docs/oxd/3.1.1/install/#centos-6](https://gluu.org/docs/oxd/3.1.1/install/#centos-6) to install oxd 3.1.1 in CentOs 6

For CentOs 6 it installs oxd 2.4.4. It should install oxd 3.1.1

**Comment by yuriyz** [comment]
solved
