### ISSUE TITLE
Packaging : oxd 3.1.1 does not work for Debian 8 OS

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#106]
While following [https://gluu.org/docs/oxd/3.1.1/install/#debian-8-jessie](https://gluu.org/docs/oxd/3.1.1/install/#debian-8-jessie)  to install oxd 3.1.1 

I am getting bellow error
Err https://repo.gluu.org jessie/main amd64 Packages
  HttpError404
Get:32 https://repo.gluu.org jessie/main Translation-en_US [328 B]
Ign https://repo.gluu.org jessie/main Translation-en_US
Get:33 https://repo.gluu.org jessie/main Translation-en [325 B]
Ign https://repo.gluu.org jessie/main Translation-en
Fetched 11.7 MB in 3s (3,352 kB/s)
W: Failed to fetch https://repo.gluu.org/debian/dists/jessie/main/binary-amd64/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@ip-172-31-20-52:/home/admin# apt-get install gluu-oxd-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gluu-oxd-server

**Comment by ebox86** [comment]
any update on this?

**Comment by willow9886** [comment]
@ebox86 this is an issue with our not-yet-released 3.1.1 packages.. it should be fine on the existing GA version.

**Comment by willow9886** [comment]
@ebox86 debian now available for oxd 3.1.1
