### ISSUE TITLE
Java Exception when Client is expired

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#108]
If a Client is expired in Gluu server and user trying to login , oxd-server is throwing error 2017-10-18 08:45:12,456 ERROR [org.xdi.oxd.server.persistence.SqlPersistenceServiceImpl] Failed to find RP by id: 3e6213ff-7ad6-420d-b474-55c2b1190b15. Error: No data is available [2000-194]
org.h2.jdbc.JdbcSQLException: No data is available [2000-194]

Here is the complete [log ](https://pastebin.com/0VfdBpmN)

oxd-server 3.1.1 (Ubuntu 16)
Glul server 3.1.1 (Ubuntu 16)

**Comment by yuriyz** [comment]
Fixed in 3.1.4.
