### ISSUE TITLE
register_site protocol

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#11]
when I send request by register_site protocol, in gluu-server added 2 clients, I think it is bug.

**Comment by willow9886** [comment]
@yuriyz this also seems like it should be tracked as oxauth issue, right?

**Comment by yuriyz** [comment]
@willow9886 it's totally oxd server problem. register_site is oxd operation to keep and track state of the site (it not referenced in oxauth in any kind).

**Comment by willow9886** [comment]
ok

**Comment by yuriyz** [comment]
Fixed in latest master.
