### ISSUE TITLE
not found classes

### ISSUE THREAD

**Issue by sakitA** [GluuFederation/oxd#110]
Hi. I download `oxd` test package and download related library such as `oxd-common` and `oxd-client` But when I compile the test project I got compile error. `RpAuthorizeRptResponse`, `RpAuthorizeRptParams` classes are not found. I checked the source code from github and did not find these class from in `oxd-common`

**Comment by centroxy** [comment]
Hi @sakitA  please mention the branch you downloaded

**Comment by sakitA** [comment]
I downloaded from this [branch](https://github.com/GluuFederation/oxd)

**Comment by centroxy** [comment]
@sakitA  Please try https://github.com/GluuFederation/oxd/tree/version_3.1.1

**Comment by nynymike** [comment]
Please post on support. And we don'e support anything but the released binaries.
