### ISSUE TITLE
update_site_registration nullifies authorization_redirect_uri if not passed as parameter

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#113]
In oxd-server **update_site_registration** command , I am passing the fields only I want to update. In this case I am not passing **authorization_redirect_uri** because this is optional field . But that nullifies the  **authorization_redirect_uri** in oxd server. I verified in Gluu server **authorization_redirect_uri** is still there.

We may need to check other fields also. As per design update_site_registration methods should only update the fields client application wants to update and  retain other values as it was before.

This issue was not in oxd 3.0.1 but in oxd 3.1.1

Environment details
Branch 3.1.1
oxd server 3.1.1
Gluu server 3.1.1

**Comment by yuriyz** [comment]
fixed in `3.1.1`
