### ISSUE TITLE
Hybrid flow : add ability to set response_type directly during authorization url request

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#114]
Hybrid flow : add ability to set response_type directly during authorization url request

**Comment by nynymike** [comment]
Is this required / allowed in the OpenID Connect spec?

**Comment by yuriyz** [comment]
yes, authorization flow is specified via `response_type`, from spec

"response_type" value | Flow
-- | --
code | Authorization Code Flow
id_token | Implicit Flow
id_token token | Implicit Flow
code id_token | Hybrid Flow
code token | Hybrid Flow
code id_token token | Hybrid Flow

**Comment by nynymike** [comment]
Right, so you are saying that regardless of what was registered, a client should be able to override in the request itself?

**Comment by yuriyz** [comment]
Right now we `register_site` with `response_type`. That response type is used during `get_authorization_url`. There is no way to pass `response_type` inside and thus change the Flow to other that was defined during registration. 

It looks as:

- If we wish to have Authorization Code Flow than we need client_1 with response_type=code. 
- If we wish in addition to have Hybrid Flow then we need another client_2 with response_type=code id_token. However it's not very flexible because for each Flow we require new client. So I believe we should do it as : register_site with response_type=`code id_token` and then in `get_authorization_url` we can pass `code` or `code id_token` defining it the flow. By default if `response_type` is not passed to `get_authorization_url` then behavior will be the same as it is now (the one that was used during registration will be used).

**Comment by yuriyz** [comment]
Done by https://github.com/GluuFederation/oxd/pull/366
