### ISSUE TITLE
Add ability to remove client from oxd

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#119]
Add ability to remove client from oxd

**Comment by willow9886** [comment]
An API for this would be very helpful, so we can give users the ability to remove clients from the oxd dashboard.

**Comment by yuriyz** [comment]
with this feature we drop RP registration from oxd only. We have experimental pull request which theoretically should allow to remove clients from oxauth but it's not clear what is the state of it. I'm going to ping it.
https://github.com/GluuFederation/oxAuth/pull/349

**Comment by yuriyz** [comment]
implemented
