### ISSUE TITLE
TOTAL AUTHENTICATION REQUESTS or TOTAL SUCCESSFUL LOGIN count do not added

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#12]
and in gluu server TOTAL AUTHENTICATION REQUESTS or TOTAL SUCCESSFUL LOGIN count do not added. it is bug too.
need add this bugs on your github account?

**Comment by yuriyz** [comment]
@dollar007 please open bug on oxauth project if you think it's bug in oxauth.

**Comment by yurem** [comment]
As far as I remember in oxAuth there is only one place where we authenticate users. In this method there is cod which increase counter: https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java#L113

@dollar007 are you make sure that you waited specified number of seconds before checking statistic?
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxauth-config.json#L217

**Comment by dollar007** [comment]
@yurem
I think it is not important for php cms's, because wordpress, magento and etc. is working via oxd-server, which is connecting to gluu server, via java language. Php is doing nothing, only connecting to oxd.
