### ISSUE TITLE
oxd License should count client applications based on number of Authorized redirect URLs

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#121]
Currently oxd license is counting Client applications based on number of client's registered on oxd server.
However there is a chance user's may setup client once and use multiple Authorized redirect url for different client applications and keep the Client Name same. In this situation oxd license will count Client application as 1 .   Not sure if this makes sense . Please fix this if required.

oxd 3.1.1

**Comment by yuriyz** [comment]
I agree. But at the time we discussed it the main argument was that oxd is open sources anyway. If we wish to make it very strict then it should not be open-sourced because for those who wish to minimize expenses can always take sources, drop license check and build license free oxd.

**Comment by yuriyz** [comment]
we dropped license handling from oxd. Close it.
