### ISSUE TITLE
oxd-https resources / packaging

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#122]
The file system layout of oxd is really weird. It does not conform with linux conventions. 

1. why is `/opt/oxd-https-extension` a top level folder in `/opt`... shouldn't it just be under `/opt/oxd/` ? 

2. `oxd-https.yml`  is in a very weird place. Create a conf folder or move it to `/opt/oxd/conf` ?

**Comment by adrian-gluu** [comment]
in latest build all the conf for oxd goes inside of /etc/oxd/oxd-server
