### ISSUE TITLE
oxAuthRedirectURI ignored after site update step

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxd#123]
When testing my webapp with newer oxd 3.1.1 (previously working fine with 3.1.0-snap), I noticed the authz URL I was getting from oxd was having `redirect_uri=null`, and thus, oxauth refused to take me to the SSO form

Example of authorization URL:
`
https://localhost:8443/oxauth/restv1/authorize?response_type=code&client_id=@!3245.DF39.6A34.9E97!0001!513A.9888!0008!00DC.5BCE.C402.C9B3&redirect_uri=null&scope=openid+profile+user_name+clientinfo&state=321le9nvkgqsrlsshlo1c9q3dr&nonce=fs443cn3o5a0alaudl0nm8r8no&acr_values=auth_ldap_server+super_gluu+u2f+otp+basic+twilio_sms`

I checked oxd tests cases and my code is doing about the same, also `oxAuthRedirectURI` was there in the LDAP client entry and `oxauth.log` was showing the right "redirect_uris" upon registration.

After an amount of trial and error I noticed that the problem was not presented if I skipped an intermediate step I was doing - consisting of a site update.

I simply added `cmdParams.setAuthorizationRedirectUri(...);` to the update routine in Java, but I don't understand why the need to repeat. It is puzzling since `oxAuthRedirectURI` is still there and the examples and tests do not give clues about the need of setting redirect_uri.

I wonder if site update is also affecting other parameters... fortunately getting tokens, userinfo, and logout is working as usual.

**Comment by yuriyz** [comment]
fixed
