### ISSUE TITLE
Setup script for oxd

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxd#126]
1. create a setup folder in the base of the oxd github repo

2. see [Gluu Gateway setup script](https://github.com/GluuFederation/gluu-gateway/blob/master/setup/setup-gluu-gateway.py) for an example of prompting for oxd license and default info and rendering the oxd config JSON files. 

3. User should be able to set the Ethernet interface and ports for `https-extension`.

**Comment by yuriyz** [comment]
@ldeveloperl1985 assigned it to you, it should be quick and easy for you to do since you already made the same for Gluu Gateway.

**Comment by yurem** [comment]
In cred-manager package we wrote this script to install oxd: https://github.com/GluuFederation/post-installation-setup/blob/master/setup_cred_mgr.py

**Comment by yurem** [comment]
These are notes related to issue from GG [issue](https://github.com/GluuFederation/gluu-gateway/issues/57):
```
oxd-setup,py --home ... -- conf ... -- license ... etc.

After running it should return exit code 0 or -1 to indicate if there is installation issues.
```

**Comment by yuriyz** [comment]
already done
