### ISSUE TITLE
Windows setup file needed for oxd service

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxd#128]
oxd should run as a service in windows. There should be a nice, easy to use installation and un-installation procedure.

**Comment by centroxy** [comment]
The development part is done. We will include oxd 3.1.2   into oxd Windows setup project once oxd 3.1.2 is ready

**Comment by duttarnab** [comment]
Closed by https://github.com/GluuFederation/oxd/pull/414 and https://github.com/GluuFederation/docs-oxd-prod/pull/83
