### ISSUE TITLE
Enable client to set custom state value

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#130]
We need some way to enable the client to set a custom `state` value, because in some cases we use the `state` value to send information to the OP.  For example, for inbound SAML IDP authentication, we set state = `{"idp":"idp.example.com", "salt":"abc123"}`

**Comment by yuriyz** [comment]
@duttarnab It should be possible to pass state to `/get-authorization-url` and to `/uma-rp-get-claims-gathering-url`. State should be added to `StateService` to pass validation correctly.

**Comment by yuriyz** [comment]
done
