### ISSUE TITLE
Misleading "ox" prefix

### ISSUE THREAD

**Issue by jcgruenhage** [GluuFederation/oxd#133]
[According to your website](https://gluu.org/docs/ce/#license), you mark open source software with your "open source handle: ox". 

I can of course understand that you don't want to release all of your code as open source, but I still wanted to point out this inconsistency. It would be great if you either make this open source (unlikely, but would be great!), or more likely just change the documentation a bit to be less misleading.

**Comment by willow9886** [comment]
Good point. I just updated that document to say:

> Gluu projects are frequently prefixed with our handle: ox

I agree it is a bit confusing, but it's too late to change now. 

Thanks for the note.

**Comment by jcgruenhage** [comment]
It wasn't meant as "change the name", that is of course out of question and would be way more confusing :D

Thanks for updating the docs :)

**Comment by willow9886** [comment]
:) my pleasure. Happy holidays!
