### ISSUE TITLE
acr_value is set in Get_authorization_url protocol 

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#14]
{
  "command":"get_authorization_url",
  "params":{
                 "oxd_id":"e43e3086-2be1-4e12-9ed9-8670aa434d55",
                 "acr_values":["basic"]
                  }
}
{
  "status":"ok",
  "data": {
               "authorization_url":"https://ce-dev.gluu.info/oxauth/authorize?                          response_type=code&client_id=@!2011.5771.5AD8.33F5!0001!7BD9.4822!0008!9BA8.6FCD&client_secret=c2ffb487-bf6a-4757-be9c-59346e804a44&redirect_uri=https://client.example.com/login&scope=openid+profile&state=af0ifjsldkj&nonce=n-0S6_WzA2Mj"
              }
}

**Comment by yuriyz** [comment]
fixed in latest oxd version with https://github.com/GluuFederation/oxd/commit/3c9eacb3f321ad6d902fae6a155c28b7834a196c

Please download fresh distribution of oxd server.
