### ISSUE TITLE
uma_rs_check_access throws invalid_scope error 

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#146]
oxd Server 3.1.2
Gluu Server 3.1.2

UMA RS Resource protection method saves the Scope expression but not the scope.
So when trying uma_rs_check_access for the resource it throws invalid_scope error 
Attached the log file.
[oxd-server_with_scope_ticket_scopeExpr.log](https://github.com/GluuFederation/oxd/files/1672570/oxd-server_with_scope_ticket_scopeExpr.log)

**Comment by yuriyz** [comment]
Unable to reproduce this ticket on ce-dev4.
Would you be so kind to check it on ce-dev4 and if it's reproducible please attach oxd-server.log file?

**Comment by centroxy** [comment]
@yuriyz  Please find the attached log file generated using ce-dev4 Gluu server 

[oxd-server_with_scope_ticket_scopeExpr.log](https://github.com/GluuFederation/oxd/files/1689415/oxd-server_with_scope_ticket_scopeExpr.log)

**Comment by centroxy** [comment]
[oxd-server.log](https://github.com/GluuFederation/oxd/files/1689445/oxd-server.log)

**Comment by yuriyz** [comment]
Re-opened

**Comment by yuriyz** [comment]
fixed in dependent uma-rs dependency, overall issue is resolved.
