### ISSUE TITLE
Move config to /etc and pid to /var/run

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#147]
Move the following files

* `/opt/oxd-server/conf`  to `/etc/oxd/oxd-server/` 
* `/tmp/oxd-server.pid` to `/var/run/oxd-server.pid`
* `/.oxd-license` to `/etc/oxd/.oxd-license` 
* `/oxd_db.mv.db` to `/var/run/oxd_db.mv.db`

**Comment by yuriyz** [comment]
Problem is that oxd-server pwd is set to root. It must be set to /opt/oxd-server.

**Comment by yurem** [comment]
This move pid to right place:
Fixed in https://github.com/GluuFederation/oxd/blob/version_3.1.2/init.d/oxd-server
Please review it.

**Comment by yurem** [comment]
Move conf folder to /etc https://github.com/GluuFederation/oxd/commit/ecc860e695766ff33b3281d1833e620e0876f0c5

**Comment by ganesh-at-wiw** [comment]
I confirm the working outside chroot.
Next is upto @adrian-gluu when he creates new package.

**Comment by yurem** [comment]
Fixed in recent oxd-server rpm/deb testing builds

**Comment by yuriyz** [comment]
database file location is changed to `/opt/oxd-server/data` according to https://github.com/GluuFederation/oxd/issues/159
