### ISSUE TITLE
oxd-server service should run oxd with user privileges instead of root

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxd#149]
Current /etc/init.d/oxd-server run java process under root. This is insecure.

Instead of updating current init.d script I offer to use jetty script with small changes. Also this will resolve issue #140

**Comment by yurem** [comment]
Fixed in https://github.com/GluuFederation/oxd/blob/version_3.1.2/init.d/oxd-server
Please review it.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/oxd/commit/92811d734da066ce470765cb84655189aae606f1#diff-e71446c8aece5dfbec371428256a5386
Works perfect inside chroot.
Now trying for outside chroot.

**Comment by ganesh-at-wiw** [comment]
Please disregard previous ocmment.
Changes are these:
https://github.com/GluuFederation/oxd/commit/1918d78978f4af3c53a11c7b9d67639f36df517f#diff-dbd88a489770c529fa83432aebcae16f
