### ISSUE TITLE
Can't able to get ticket in second time same resource registration by other client

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxd#150]
Reproduce the problem
1. Register client(setup_client)
2. Register resources first time as below request /uma-rs-protect
```
{  
   
      "oxd_id":"<oxd-id-1>",
      "resources":[  
         {  
            "path":"/posts",
            "conditions":[  
               {  
                  "httpMethods":[  
                     "GET"
                  ],
                  "scopes":[  
                     "https://jsonplaceholder.typicode.com"
                  ],
                  "scope_expression":null
               }
            ]
         }
      ]
}
```

3. request to /uma-rs-check-access and gets success response
```
{
    "status": "ok",
    "data": {
        "access": "denied",
        "ticket": "d8d9f335-d44e-4854-9cca-abb73755bda8",
        "www-authenticate_header": "UMA realm=\"rs\",as_uri=\"https://gluu.local.org\",error=\"insufficient_scope\",ticket=\"d8d9f335-d44e-4854-9cca-abb73755bda8\""
    }
}
```

4. Then delete this resource and scope from gluu server using oxtrust

5. Again make new client(setup_client)

6. Again register resources with same request /uma-rs-protect with new oxd_id
```
{  
   
      "oxd_id":"<oxd-id-2>",
      "resources":[  
         {  
            "path":"/posts",
            "conditions":[  
               {  
                  "httpMethods":[  
                     "GET"
                  ],
                  "scopes":[  
                     "https://jsonplaceholder.typicode.com"
                  ],
                  "scope_expression":null
               }
            ]
         }
      ]
}
```

7. Request to /uma-rs-check-access and gets error response
oxd-server.log shows below error(same error which we faced yesterday)

```
2018-02-06 14:46:52,186 ERROR [org.xdi.oxd.server.Processor] RESTEASY003150: Error status 404 Not Found returned
org.jboss.resteasy.client.ClientResponseFailure: RESTEASY003150: Error status 404 Not Found returned
```

Overall, if we register the same resource and scope second time with other oxd-id, then it doesn't allow gets ticket and throws this below error.  [oxd-server.log](https://github.com/GluuFederation/oxd/files/1698968/oxd-server.log)

Just for info: I've deleted the oxd-server DB and again tried with fresh client registration and above same resource registration request. it works well

[oxd-server.log](https://github.com/GluuFederation/oxd/files/1698968/oxd-server.log)

**Comment by yuriyz** [comment]
I believe you've tried to catch 404 error which we discussed in skype. However your log show's Jajati's issue described here https://github.com/GluuFederation/oxd/issues/146

Please make sure you got 404 and please attache oxd-server.log against ce-dev4.

**Comment by ldeveloperl1985** [comment]
Okay Just tested with ce-dev4 and got 404 
[oxd-server.log](https://github.com/GluuFederation/oxd/files/1699060/oxd-server.log)

**Comment by yuriyz** [comment]
fixed
