### ISSUE TITLE
oxd-https-extension does not log 

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#151]
oxd v 3.1.2

When start oxd-https-extension it logs  it logs till starting of oxd-https-extension. 
But no logging after that . 

Please check the below log file

[oxd-https-extension log](https://s3.amazonaws.com/uploads.hipchat.com/714532/5024693/qiSGMNllI2Dw99Q/application_oxd312_Gluu311.log)

**Comment by yuriyz** [comment]
it's because there is nothing to log basically, it's just http proxy to oxd server. If you think there should be some specific logs in oxd-https-extension then lets discuss it.

**Comment by centroxy** [comment]
@yuriyz  Before, it used to log the method names, so we know if https-extension is getting called or not. Also if any error will it log ?

**Comment by yuriyz** [comment]
yes, it should log errors. We do not log method names on call anymore. To check whether oxd-https-extension is live you can use /health-check endpoint. This is the purpose of it.
