### ISSUE TITLE
Update build from lasdtest build files

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxd#157]
We need to put into build folder updated debian/rpm package manager files. Also we can changes structure like this:
```
build
 |- deb
 |-rpm
```

**Comment by adrian-gluu** [comment]
we couldn't reproduce this error of uninstall on latest build:
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/oxd-server_3.1.2-32~trusty+Ub14.04_all.deb
