### ISSUE TITLE
Move database to /db folder

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#159]
I see .db files in the `/opt/oxd-server/bin/` folder. 
![image](https://user-images.githubusercontent.com/3717101/36347821-1a5bf51a-1427-11e8-9cac-ece5687c7a70.png)

Perhaps we should create a db folder in `/opt/oxd-server`? It could also go in `/var/spool/oxd`

**Comment by yuriyz** [comment]
@nynymike according to https://github.com/GluuFederation/oxd/issues/147 db file is moved to `/var/run/oxd_db.mv.db`. Change should be present in latest package generated by Adrian for testing for trusty.

**Comment by ganesh-at-wiw** [comment]
shouldn't oxd_db.mv.db go to somewhere like: /opt/oxd-server/db/ or some similar location instead of /var/run/ where usually runtime data goes?

**Comment by yuriyz** [comment]
if we want something more app specific and generic then I propose to put it in /opt/oxd-server/data folder.

**Comment by yurem** [comment]
From my point of view `/opt/oxd-server/data` or ``/var/lib/oxd-server`` is more persistence than `/var/spool/oxd`. For example `/var/spool/mail` mail daemon uses to store mail queues.

**Comment by yuriyz** [comment]
changed db file location to `/opt/oxd-server/data` in 3.1.2
