### ISSUE TITLE
There are many duplicate files created in oxd repo by Adrian. We must not produce duplicates in source code.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#161]
Duplicates produced by this commit:
https://github.com/GluuFederation/oxd/commit/44b9c1abb0335229f97c8b64aac287757c4f1ee9

![filestoremove](https://user-images.githubusercontent.com/2013070/36496208-3f90bd04-1740-11e8-9aef-e6be75c63d8e.png)

**Comment by adrian-gluu** [comment]
I just run it mvn clean, to clean all the duplicates files and commit the changes

**Comment by yuriyz** [comment]
duplicates are still there https://github.com/GluuFederation/oxd/tree/version_3.1.2/conf

**Comment by yuriyz** [comment]
I removed it.
