### ISSUE TITLE
Add description and oxdID to client metadata

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#162]
It is hard to tell which oxdID corresponds to which client. I added  https://github.com/GluuFederation/oxAuth/issues/754 to request a `description` and `oxdID` field to client metadata. This is a corresponding feature request to send that data during registration and update. `description` is there for a rainy day.

**Comment by yuriyz** [comment]
done by https://github.com/GluuFederation/oxd/pull/367
