### ISSUE TITLE
Write init.d script for oxd https extension

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxd#164]
Current oxd [https](https://github.com/GluuFederation/oxd/blob/master/debian/oxd-https-extension.init.d) init script is in spartan style. We need write fully functional script before building final packages. We can use oxd [script](https://github.com/GluuFederation/oxd/blob/master/debian/oxd-server.init.d) as reference.

**Comment by ganesh-at-wiw** [comment]
What is the meaning of fully functional?

**Comment by yurem** [comment]
1. It should allow to configure it via use /etc/default/service_file.
2. It should works fine CentOS/Ubuntu/Debian/etc..
3. Why nohip is better that start-stop-daemon ?

**Comment by ganesh-at-wiw** [comment]
Yes that makes sense.

**Comment by ganesh-at-wiw** [comment]
This is the first version.
We'll test and improve it once few parameters change.
https://github.com/GluuFederation/oxd/commit/c76f80e774a6c880d67f8f9fcb0302be733ae070#diff-5b09d5a3138daedc214d56ce1b66dda2

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/oxd/commit/a20d1855968b98e5e2eb3ed067049fb2ee862a1f#diff-5b09d5a3138daedc214d56ce1b66dda2
https://github.com/GluuFederation/oxd/commit/26da3bf1d49108b69b44b2e7ddbd498697770410#diff-2855a1e7ebf5bfbbb1de097ee47e2798

Few updates to get extension working. More updates will be done with the help of @yurem once he gets new changes introduced in oxd-https-extension package.
