### ISSUE TITLE
UMA : add creation and expiration resource support to oxd

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#165]
https://github.com/GluuFederation/oxAuth/issues/755

**Comment by duttarnab** [comment]
@yuriyz , as per my understanding we need to save `iat` and `exp` date of uma resources from op_host to oxd storage. Please confirm.

**Comment by yuriyz** [comment]
Main part is to be able specify creation/expiration dates during UMA resource creation. Add these dates to command and if it's not specified then it should work as it is working now.

**Comment by duttarnab** [comment]
@yuriyz, one doubt here is oxauth is saving `iat,exp` passed from oxd.  It is creating its own date. Please advise.

https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/uma/ws/rs/UmaResourceRegistrationWS.java#L314

**Comment by yuriyz** [comment]
@duttarnab you are right, I've created ticket and will fix it today https://github.com/GluuFederation/oxAuth/issues/1277

**Comment by duttarnab** [comment]
@yuriy, another thing is in below line `resource.getIat()` (i.e. `org.gluu.oxauth.model.uma.UmaResource.iat` and `org.gluu.oxauth.model.uma.UmaResource.exp`) should be `long`. If it is int then `new Date(resource.getIat() * 1000);` donot returns correct date value.

https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/uma/ws/rs/UmaResourceRegistrationWS.java#L305

**Comment by yuriyz** [comment]
@duttarnab fixed in https://github.com/GluuFederation/oxAuth/commit/9a65f7b53f708fb607c783011d6429672df5b29b

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/uma-rs/pull/3 , https://github.com/GluuFederation/oxd/pull/427 and https://github.com/GluuFederation/docs-oxd-prod/pull/85
