### ISSUE TITLE
oxd-server should exist with not zero error code on initialization error

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxd#168]
According to [this](https://softwareengineering.stackexchange.com/questions/20573/why-does-java-exit-with-success-after-an-uncaught-exception) it returns 0 even if it stop at uncaught exception. It should return non zero exit code in such cases.

**Comment by yuriyz** [comment]
Done for 3.1.3

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/oxd/commit/100fe87f1678d99ed50981b64347f758fb961189#diff-f5431d0105df35d0716cf9e4f91f2d7d
This takes care of the error exit codes.
