### ISSUE TITLE
oxd throwing error when ID tokens audience claim represented as array with single value

### ISSUE THREAD

**Issue by bhammond604** [GluuFederation/oxd#178]
According to the RFC 7519 specifications (https://tools.ietf.org/html/rfc7519), the value of the ID token's audience claim can be either an array or a string, however, when the audience token is represented as an array with a single value, oxd gives the following error. 

`ID Token has invalid audience. Expected audience: AUDTOKEN, audience from token is: ["AUDTOKEN"]`

This has caused issues when testing oxd against the OpenID testing tool (https://github.com/openid-certification/oidctest).

If oxd is faced with an audience claim that is being represented as an array with only a single value, it should convert it from an array into a string.

**Comment by yuriyz** [comment]
It has nothing to do with oxd, id_token is constructed on oxauth/AS side. Please open ticket on oxauth project.

**Comment by willow9886** [comment]
@yuriyz we're not testing against oxAuth.. we're testing against the OpenID Connect RP certification tool.

**Comment by yuriyz** [comment]
done in 3.1.4, please test on oxd from maven https://ox.gluu.org/maven/org/xdi/oxd-server/3.1.4-SNAPSHOT/

**Comment by vnikolaou** [comment]
[log0.txt](https://github.com/GluuFederation/oxd/files/1985782/log0.txt)

**Comment by vnikolaou** [comment]
The previous log file (log0.txt) contains line from the oxd-server.log of the new version 3.1.4 . I run the test from the client web app (ie. trying to get a token from a code) but again i am getting the same error:

2018-05-09 00:47:57,181 ERROR [org.xdi.oxd.server.op.Validator] ID Token has invalid audience. Expected audience: gswuZoTVeFGg, audience from token is: ["gswuZoTVeFGg"]

Am i missing anything in installing the new version properly? The log file indicates that i am running the correct (new) version..

**Comment by yuriyz** [comment]
@vnikolaou thank for this report, I checked logs and version is correct but somehow it didn't take aud as list array, so I've added trick to check this single valued array and refreshed oxd server version on maven. Please donwload it again and report whether it works for you or not. Thanks!

https://ox.gluu.org/maven/org/xdi/oxd-server/3.1.4-SNAPSHOT/oxd-server-3.1.4-SNAPSHOT-distribution.zip

**Comment by vnikolaou** [comment]
Hi @yuriyz . Yes the new version seems to be working around this particular issue. Thanks too. 
I'll let you know if i see other issues.
