### ISSUE TITLE
`postLogoutRedirectUrl` should be taken from site registration of it is absent in `get_logout_uri` command

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#179]
`postLogoutRedirectUrl` should be taken from site registration of it is absent in `get_logout_uri` command

**Comment by yuriyz** [comment]
done for 3.1.4

**Comment by natt-tester** [comment]
Checked in 3.1.4: it's done.
<img width="817" alt="get_logout" src="https://user-images.githubusercontent.com/38302725/47018586-c0895b80-d1a0-11e8-8faf-0d808ce752c7.png">
