### ISSUE TITLE
Add tracing metrics to oxd server

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#182]
http://opentracing.io/documentation/pages/instrumentation/instrumenting-frameworks

**Comment by duttarnab** [comment]
Steps to enable tracing in oxd-server

https://github.com/GluuFederation/oxd/wiki/Add-tracing-metrics-to-oxd-server

**Comment by yuriyz** [comment]
@duttarnab it's nice to have wiki but would you be so kind to add it also to our oxd docs ? (in 4.1 version)

**Comment by duttarnab** [comment]
Done by https://github.com/GluuFederation/oxd/pull/385
