### ISSUE TITLE
Enhancement: "shutted" to "shut"

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#186]
Please refer to the screenshot of the message I got after not configuring the server name and running the oxd server. Change the string to "shut" :)

![2018-05-26_18h15_32](https://user-images.githubusercontent.com/38302725/40575450-8aec702c-6128-11e8-8424-ce209f5f2687.png)

**Comment by yuriyz** [comment]
Fixed in 3.1.4, thanks for report !

**Comment by natt-tester** [comment]
I see the fix, and I can't reproduce the error in GG 3.1.4 +oxd-server 3.1.4. It's done.
