### ISSUE TITLE
Bug: no billing for Gluu Gateway Consumers

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#188]
I created 3 different Consumers with unique oxd_ids in GG Admin Panel, but I don't see any billing connected with their creation in the oxd ecom portal. Shouldn't each of them generate 1 unit/day?

**Comment by yuriyz** [comment]
please re-open on https://github.com/GluuFederation/ecommerce-python

**Comment by ldeveloperl1985** [comment]
Agreed with Natalia, 3 diff consumer creates 3 diff clients. each of them should generate 1 unit/day.
