### ISSUE TITLE
Bug: inconsistent billing report for 3 gluu-oauth2-client-auth plugin APIs

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#189]
Steps:
1. Log in to the GG Admin Portal
2. Go to APIs and create 3 APIs with the gluu-oauth2-client-auth plugin
3. Wait 2 days 
4. Check the oxd ecom portal

Expected: Each API should generate 1 unit/day, so I expect to see 6 used units.
Actual: There are 2 units used.

Please investigate it.

**Comment by yuriyz** [comment]
please re-open on https://github.com/GluuFederation/ecommerce-python
