### ISSUE TITLE
add oxd-stop.sh, oxd-stop.bat file in oxd-server folder

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#19]
If there is a start script, there should be a stop script too. Perhaps we could use an init.d script here?

**Comment by nynymike** [comment]
agreed... I also noticed this was missing.

**Comment by willow9886** [comment]
@adrian-gluu can you comment on whether you can take care of this issue by this Friday (Feb 12) ?

**Comment by yuriyz** [comment]
seems to be done by @adrian-gluu . Closing it for now.
