### ISSUE TITLE
Bug: License Details copied with enters

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#190]
Please refer to the GIF and fix the Copy feature for **Public Key**, **Public Password**, **License Password** and **Copy all license details**. Now it's quite inconvenient UX-wise.

![2018-05-28_13h48_42](https://user-images.githubusercontent.com/38302725/40596569-247ca55c-627f-11e8-9951-6df897fef37d.gif)

**Comment by yuriyz** [comment]
please re-open on this project https://github.com/GluuFederation/ecommerce-python
