### ISSUE TITLE
Bug: OP host stored as oxd server name

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#193]
I think that the server name stored during the oxd-server installation with Gluu Gateway is wrong. 
During the setup, the user is asked for **OP server name**, so I put ce-dev6.gluu.org there. 
The setup also asks for the **oxd https url**, which by default is https://osboxes.org:8443 for me. After accepting these values, the JSON config files show ce-dev6.gluu.org for both server_name and op_host. 
It seems that after changing the name the values visible in the ecom platform don't change.  Please correct me if I'm wrong :)

![2018-06-01_14h31_05](https://user-images.githubusercontent.com/38302725/40885200-0b1a9778-6765-11e8-9853-5d00054c5bbe.png)
![2018-06-03_19h46_45](https://user-images.githubusercontent.com/38302725/40885290-feff0fa8-6766-11e8-9559-e046c0c78bc0.png)
![2018-06-03_19h46_38](https://user-images.githubusercontent.com/38302725/40885291-00ec2814-6767-11e8-9be5-f34b010f8e21.png)
![2018-06-03_19h52_36](https://user-images.githubusercontent.com/38302725/40885350-df757112-6767-11e8-918b-f468565edf6a.png)
![2018-06-03_19h52_06](https://user-images.githubusercontent.com/38302725/40885352-e926181a-6767-11e8-916a-fa7f3a2b0e42.png)

**Comment by ganesh-at-wiw** [comment]
Hi @yuriyz , is the issue really for us or should it go to Meg?

**Comment by yuriyz** [comment]
@ganesh-at-wiw bug seems to be in setup script, it would be nice if you can check it since Meg is quite busy with GG right now.

**Comment by ganesh-at-wiw** [comment]
Hello @natt-tester and @yuriyz and @ldeveloperl198,
I've introduced two changes here:
1. oxd-conf.json template, I've introduced new variable: 
root@vsurpr0001:/opt/gluu-gateway/setup# cat /opt/gluu-gateway/setup/templates/oxd-conf.json |grep server_name
  "server_name": "%(oxdHost)s",

2. This name oxdHost is derived from 'oxd https url ' value inside setup script.

@natt-tester please try to use these files while testing 3.1.3.


Place these attached files as:
/opt/gluu-gateway/setup/templates/oxd-conf.json
and 
/opt/gluu-gateway/setup/setup-gluu-gateway.py

before running the setup and let me know your results.
I'm updating the github as well.

**Comment by ganesh-at-wiw** [comment]
@natalia below are for your reference.

https://github.com/GluuFederation/gluu-gateway/commit/ed60675a779e51c78c0c34f1807e15c98a1f6c23#diff-1dba37cbcbf0173e73367d6e008cb78a
https://github.com/GluuFederation/gluu-gateway/commit/30b52025578a80dae3b70367f678d04025b8bac7#diff-a747cca51cfc2592e20063b787d3b0ca

**Comment by ldeveloperl1985** [comment]
@ganesh-at-wiw I've merged changes and tested. Set server_name works. 
@natt-tester please test on your side by replacing this files.
https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.4/setup/templates/oxd-conf.json
https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.4/setup/setup-gluu-gateway.py

**Comment by natt-tester** [comment]
@ganesh-at-wiw, @ldeveloperl1985, I've been testing it quite thoroughly and I see that after a successful setup there's no record of my vm in the oxd ecom platform... Can you inspect the logs and tell me if I'm doing everything correctly?

[oxd-server.log](https://github.com/GluuFederation/oxd/files/2140900/oxd-server.log)

[oxd-conf.json.zip](https://github.com/GluuFederation/oxd/files/2140912/oxd-conf.json.zip)
[setup.zip](https://github.com/GluuFederation/oxd/files/2140913/setup.zip)

**Comment by ganesh-at-wiw** [comment]
We could need separate ssl cert for oxd server if we use separate name for oxd-server at our gg server.

**Comment by natt-tester** [comment]
@yuriyz, @ldeveloperl1985  Tested in GG 3.1.4 + oxd-server 3.1.4: the servver_name is changed indeed, but due to #240 I think it should be also removed here.

**Comment by yuriyz** [comment]
@ldeveloperl1985 can you correct setup script for GG and remove `server_name` (we don't have it anymore in oxd) ?

**Comment by ldeveloperl1985** [comment]
Okay, I'll update setup script. @natt-tester can you please create issue in GG.
