### ISSUE TITLE
Migrate to swagger 3.0 once swagger-codegen has stable release

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#195]
Right now for 3.2.0 we stick to swagger 2.0 spec which is current stable version. There are no support for 3.0 by codegen project yet.

https://github.com/swagger-api/swagger-codegen

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxd/issues/181

**Comment by yuriyz** [comment]
@duttarnab I'm moving migration to swagger 3.0 to 4.2 since we don't have much tickets left on oxd. Before we consider moving to 3.0 please check following:

- check whether swagger codegen is released and stable
- code simple yml with one operation and try whether generate code is correct.

If we got positive answers for these two then we can migrate oxd to swagger 3.0.

**Comment by duttarnab** [comment]
- check whether swagger codegen is released and stable
@yuriyz, I think `OpenAPI 3.0` is released
https://swagger.io/blog/news/announcing-openapi-3-0/

-  simple yml with one operation and try whether generate code is correct.
I am checking this.

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/416
