### ISSUE TITLE
Deploy beta oxd-server 3.2.0 and swagger-ui to gluu.org server.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#196]
We need to have oxd-server 3.2.0 and swagger-ui picked up live. After short discussion with @willow9886 it was decided to keep it on the same server as docs (https://gluu.org/docs/oxd/3.0.1/)

*Swagger IU*
For now we need swagger UI available at `https://gluu.org/swagger-ui`. (see `https://swagger.io/tools/swagger-ui/`)
It should look as this live demo `http://petstore.swagger.io/?_ga=2.18949564.500463045.1528366923-1428395997.1528268788`

*oxd-server live*
Also we need oxd-server 3.2.0 available live.
`https://gluu.org/oxd/3.2.0` (keep in mind that in future we will need `https://gluu.org/oxd/3.3.0` and so on)

To start oxd-server 3.2.0
1. download jar http://ox.gluu.org/maven/org/xdi/oxd-server/3.2.0-SNAPSHOT/oxd-server-3.2.0-SNAPSHOT.jar
2. download yml file 
3. take keystore file or generate new `https://github.com/GluuFederation/oxd/blob/version_3.2.0/oxd-server/src/main/resources/oxd-server.keystore`
4. modify `oxd-server-dev.yml` to point to keystore file
5. run it as `java -jar oxd-server-3.2.0-SNAPSHOT.jar oxd-server-dev.yml` (as defined in yml file logs should be in `/var/log/oxd-server.log` or you can put other location)

If all works well then if you hit in browser `https://gluu.org/oxd/3.2.0/health-check` it should return `running`.

**Comment by yuriyz** [comment]
@ganesh-at-wiw our next major release is going to be 4.0.0 instead of 3.2.0. Please change 3.2.0 -> 4.0.0

**Comment by yuriyz** [comment]
Otherwise nice work !

**Comment by yuriyz** [comment]
done

**Comment by ganesh-at-wiw** [comment]
Swagger is available as:
https://gluu.org/swagger-ui/

Two samples prepared for /oxd/version. The OXD server installation has been carried out on oxd-live.gluu.org. Proxies work as below:

https://gluu.org/oxd/3.2.0/health-check is proxied to https://oxd-live.gluu.org/oxd/3.2.0/health-check
https://gluu.org/oxd/3.2.1/health-check is proxied to https://oxd-live.gluu.org/oxd/3.2.1/health-check
