### ISSUE TITLE
Add client_token_endpoint_auth_signing_alg parameter during registration

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#197]
https://github.com/GluuFederation/gluu-gateway/issues/19

**Comment by yuriyz** [comment]
done for 3.1.4 and master

**Comment by natt-tester** [comment]
Checked in 3.1.4: it's done.
<img width="949" alt="ubuntu14_oxd3 1 4_signingalg" src="https://user-images.githubusercontent.com/38302725/46998758-396fbf80-d16f-11e8-8606-465b4ad9df5c.png">
