### ISSUE TITLE
Provide ability to pass different names for setup client and normal client in `setup_client` command

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#200]
Provide ability to pass different names for setup client and normal client in `setup_client` command

**Comment by yuriyz** [comment]
done in 3.1.4

**Comment by natt-tester** [comment]
Checked in 3.1.4: it's done. You can pass both the same and different names.
<img width="487" alt="name1" src="https://user-images.githubusercontent.com/38302725/46995561-ff012500-d164-11e8-862e-a75f68a2b7ad.png">
<img width="1172" alt="clients" src="https://user-images.githubusercontent.com/38302725/46995572-07f1f680-d165-11e8-8522-09bf76ab73ff.png">
