### ISSUE TITLE
Bug: can't log in to oxd

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#203]
Steps:

1. Go to https://oxd.gluu.org/
2. Click on Login

Expected: I see a login screen
Actual: There's an error message:

![2018-07-02_17h59_30](https://user-images.githubusercontent.com/38302725/42152071-6a67576a-7e22-11e8-92fa-5856be27f1a9.png)

**Comment by yuriyz** [comment]
@natt-tester I can login without problems. Can you give exact steps that leads to this problem?

**Comment by natt-tester** [comment]
![2018-07-02_19h28_22](https://user-images.githubusercontent.com/38302725/42156845-7f937bca-7e2f-11e8-95a1-779d16e855d8.gif)

**Comment by jajatibadu-webee** [comment]
@natt-tester  you need to check your  host file entry. May be in your pc's host file https://idp.gluu.org is mapped to other IP. 

Jajati

**Comment by centroxy** [comment]
@natt-tester you need to check your host file entry. May be in your pc's host file https://idp.gluu.org is mapped to other IP.

Jajati

**Comment by natt-tester** [comment]
Thanks Jajati, it was exactly the cause. It seems I had leftovers from previous tests :)
