### ISSUE TITLE
Minor : lowercase autogenerated client name, oxD -> oxd

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#204]
Minor : lowercase autogenerated client name, oxD -> oxd

**Comment by yuriyz** [comment]
done for 3.1.4

**Comment by natt-tester** [comment]
Checked in 3.1.4: done.
<img width="523" alt="client_name" src="https://user-images.githubusercontent.com/38302725/46795885-f9879180-cd96-11e8-9125-33ecc25136f2.png">
