### ISSUE TITLE
Change scope for oxd API access

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#205]
I think the scope for calling oxd api's should be "oxd" not "uma_protection"

**Comment by yuriyz** [comment]
done for 3.1.4 and 4.0.0

**Comment by sahiliamsso** [comment]
![image](https://user-images.githubusercontent.com/21104811/44313338-83188400-a424-11e8-8a6d-b9e40e7162ff.png)

It seems changes are not available in 3.1.4.

**Comment by yuriyz** [comment]
it is present in setup, see here https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.4/templates/scopes.ldif#L108

Are you sure you have 3.1.4 installed? Otherwise it something with the package.

**Comment by yuriyz** [comment]
the last to commits has bad links, it should be linked to https://github.com/GluuFederation/oxAuth/issues/824

**Comment by natt-tester** [comment]
@yuriyz The scope itself is present in CE, but could you humor me and shed more light on why the following didn't work?

Steps:
1. Setup_client call:
```
{
  "authorization_redirect_uri": "http://localhost:5000/callback",
  "op_host": "https://bla.gluu.org",
  "client_name": "new6", 
  "response_types": ["code"],
  "grant_types": ["authorization_code", "client_credentials"],
  "scopes":["openid", "oxd"]
}
{
    "status": "ok",
    "data": {
        "oxd_id": "e7cc3f58-f5e3-431d-a163-8d6ebd95403b",
        "client_id_of_oxd_id": "@!A135.941F.C631.BFE7!0001!4B20.7D2D!0008!C15A.34A1.5B70.D776",
        "op_host": "https://bla.gluu.org",
        "setup_client_oxd_id": "dcbbafc2-5a03-46a0-80b8-de485c5daf1f",
        "client_id": "@!A135.941F.C631.BFE7!0001!4B20.7D2D!0008!4BF1.5E36.3EB6.F796",
        "client_secret": "69c3c574-f25a-4a93-accd-d283f98ce693",
        "client_registration_access_token": "0f47b3ad-dd04-4f54-a7b1-ccc624893907",
        "client_registration_client_uri": "https://bla.gluu.org/oxauth/restv1/register?client_id=@!A135.941F.C631.BFE7!0001!4B20.7D2D!0008!4BF1.5E36.3EB6.F796",
        "client_id_issued_at": 1539866375,
        "client_secret_expires_at": 1539952775
    }
}
```
2. Check CE for scopes: uma_protection, permission, oxd, openid are there by default
3. get_client_token call:
```
{
    "op_host" : "https://bla.gluu.org",                                        
    "client_id": "{{clientID}}",
    "client_secret": "{{clientSecret}}",
    "scope": ["openid", "oxd"]
}

{
    "status": "ok",
    "data": {
        "scope": "openid oxd",
        "access_token": "734862eb-087c-432b-9006-e36d46645de8",
        "expires_in": 299,
        "refresh_token": null
    }
}
```
4. register_site — 200 OK Internal Error -- btw, can we change the code to something different? It really looks confusing
```
{
    "authorization_redirect_uri": "http://localhost:5000/callback",
    "op_host":"https://bla.gluu.org",
    "grant_types": ["authorization_code"],
    "response_types": ["code", "token"],
    "protection_access_token": "{{clientToken}}"
}
{
    "status": "error",
    "data": {
        "error": "internal_error",
        "details": null,
        "error_description": "Unknown internal server error occurs."
    }
}
```
6. Setup_client + get_client_token with the openid scope only
```
{
    "status": "ok",
    "data": {
        "scope": "openid",
        "access_token": "ac7a08ec-d0d6-4472-8b60-f41dbc899af7",
        "expires_in": 299,
        "refresh_token": null
    }
}
```
7. register_site still doesn't work, but update_site does:
```
{
    "oxd_id":"{{oxdID}}",
    "response_types": ["code", "token"]
}
{
    "status": "ok",
    "data": {
        "oxd_id": "47a26f64-c041-45b5-88f0-97589a253fcd"
    }
}
```
The docs say "In 3.1.4 we have forced users to have the oxd scope associated with protection_access_token. If it is not present, then oxd rejects the calls."
"protect_commands_with_access_token":true in my config

**Comment by yuriyz** [comment]
First of all `setup_client` and `get_client_token` are commands to get access, so they are NOT protected. In this ticket I think you wish to validate `oxd` scope presence. For this you can use any other command from protocol, for example `get_authorization_url`.

Step 4 looks exactly the same as here https://github.com/GluuFederation/oxd/issues/201#issuecomment-431058558. Lets use same OP as I've suggested in chat to narrow the problem.

About 200. In sockets we encoded error in the protocol itself. In oxd 4.0 we dropped sockets and stick to REST calls only. There if error occurs you will always get appropriate HTTP code, in 3.1.4 it is not the case unfotunately.

**Comment by natt-tester** [comment]
Ok, to validate the oxd presence and that it works well:

- setup_client is 200 OK with the following:
```
{
  "authorization_redirect_uri": "http://localhost:5000/callback",
  "op_host": "https://ce-dev3.gluu.org",
  "client_name": "new2", 
  "response_types": ["code"],
  "grant_types": ["authorization_code", "client_credentials"],
  "scopes":["openid"]
}
```
- get_client_token is OK:
```
{
    "op_host" : "https://ce-dev3.gluu.org",                                        
    "client_id": "{{clientID}}",
    "client_secret": "{{clientSecret}}",
    "scope": ["openid"],
    "grant_types": ["authorization_code", "client_credentials"]
}
{
    "status": "ok",
    "data": {
        "scope": "openid",
        "access_token": "95f55904-fd3b-4b8d-87e9-05b32fd0dc90",
        "expires_in": 299,
        "refresh_token": null
    }
}
```
- register_site is OK, but there's no oxd scope:
```
{
    "authorization_redirect_uri": "http://localhost:5000/callback",
    "op_host":"https://ce-dev3.gluu.org",
    "grant_types": ["authorization_code", "client_credentials"],
    "response_types": ["code", "token"],
    "protection_access_token": "{{clientToken}}"
}
{
    "status": "ok",
    "data": {
        "oxd_id": "5d946a2c-c028-4e05-ab08-edc1975ea55c",
        "op_host": "https://ce-dev3.gluu.org"
    }
}
```
- get-authorization-url fails, there's no oxd scope:
```
{
    "oxd_id": "{{oxdid}}"

}
{
    "status": "error",
    "data": {
        "error": "protection_access_token_insufficient_scope",
        "details": null,
        "error_description": "protection_access_token does not have oxd scope. Make sure a) scope exists on AS b) setup_client is registered with 'oxd' scope c) get_client_token has 'oxd' scope in request"
    }
}
```
Why didn't register_site fail, then?

**Comment by yuriyz** [comment]
It must fail too, it is due to special handling of `register-site` because of association between oxd_id and client_id. Fixed it.

**Comment by natt-tester** [comment]
Tested with the new oxd-server-jar-with-dependencies.jar -- without the **oxd** scope in the token all oxd calls but `update_site` fail. When the scope is present, they are successful.
