### ISSUE TITLE
Bad URL in oxd error messages

### ISSUE THREAD

**Issue by bhammond604** [GluuFederation/oxd#208]
Some oxd error messages are prompting the user to go to https://www.gluu.org/docs-oxd. oxd documentation is at https://gluu.org/docs/oxd.

The error:
`OxdServerError: oxd Server Error: invalid_uma_request
 Resources list to protect is empty or blank. Please check it according to protocol definition at https://www.gluu.org/docs-oxd`

**Comment by yuriyz** [comment]
Thanks for report, fixed in 3.1.4 and 4.0.0.

**Comment by natt-tester** [comment]
Checked in 3.1.4: done.
<img width="1297" alt="docs_path" src="https://user-images.githubusercontent.com/38302725/46792100-4024be00-cd8e-11e8-9d1c-a995291eb449.png">
