### ISSUE TITLE
oxd-server skips access_token validation only if protect_commands_with_access_token=false and protection_access_token is not provided.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#213]
oxd-server skips access_token validation only if protect_commands_with_access_token=false and protection_access_token is not provided.

This behavior is confusing. We need to change it and do not validate access_token even if it is provided when 
protect_commands_with_access_token=false

**Comment by yuriyz** [comment]
done

**Comment by natt-tester** [comment]
Checked in 3.1.4 + Ubuntu 14: it's done.
