### ISSUE TITLE
We have to adapt oxd introspection response `scopes` -> `scope` according to oxauth changes

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#214]
Change on oxauth is made here:
https://github.com/GluuFederation/oxAuth/issues/852

**Comment by yuriyz** [comment]
done for both 3.1.4 and 4.0.0

**Comment by natt-tester** [comment]
Checked in 3.1.4: done.
<img width="635" alt="scope" src="https://user-images.githubusercontent.com/38302725/46789910-6f84fc00-cd89-11e8-8f34-8b834a0150b6.png">
