### ISSUE TITLE
Allow to build oxd without git

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#215]
As reported in support ticket if download project as zip and run maven plugin it fails due to absence of `.git` directory which is automatically created during `git clone`
https://support.gluu.org/other/5770/java-sample-wont-build/#at36402

There are two solutions:

- `git clone`
- add `<failOnNoGitDirectory>false</failOnNoGitDirectory>` to `git-commit-id-plugin` plugin configuration

**Comment by yuriyz** [comment]
done in 3.1.4

**Comment by natt-tester** [comment]
Checked in 3.1.4: done.
<img width="1375" alt="ubuntu16_oxd3 1 4_maven_build" src="https://user-images.githubusercontent.com/38302725/46949668-ef82cd00-d0cd-11e8-8f37-93304fdd9daf.png">
