### ISSUE TITLE
Do not provide id_token_hint in logout uri to force logout by session_id cookie if oxauth #831 issue is fixed.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#223]
Do not provide id_token_hint in logout uri to force logout by session_id cookie if oxauth #831 issue is fixed.

https://github.com/GluuFederation/oxAuth/issues/831

**Comment by yuriyz** [comment]
done

**Comment by natt-tester** [comment]
Checked in 3.1.4: it's done.
<img width="826" alt="call" src="https://user-images.githubusercontent.com/38302725/46945995-176c3380-d0c2-11e8-8dbc-349688e5ea51.png">
