### ISSUE TITLE
Drop "status" from protocol for all commands that was used by sockets. In REST it is covered by HTTP status.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#225]
Drop "status" from protocol that was used by sockets. In REST it is covered by HTTP status.

Instead of 
```json
{
    "status":"ok",
    "data":{
        "access_token":"SlAV32hkKG",
        "expires_in":3600,
        "refresh_token":"aaAV32hkKG1",
        ...
    }
}
```
Return
```json
HTTP/1.1 200 OK
{
    "access_token":"SlAV32hkKG",
    "expires_in":3600,
    "refresh_token":"aaAV32hkKG1",
    ...
}
```

Also we need to move error handling to REST style.

Instead of
```
{
    "status":"error",
    "data":{
        "error":"invalid_request",
        "error_description":"Resource is not protected. Please protect your resource first with uma_rs_protect command."
    }
}
```
Return
```json
HTTP/1.1 400 OK
{
    "error":"invalid_request",
    "error_description":"Resource is not protected. Please protect your resource first with uma_rs_protect command."
}
```

**Comment by yuriyz** [comment]
done

**Comment by natt-tester** [comment]
Tested in 4.0beta: the status is dropped:

<img width="1068" alt="invalid_oxd" src="https://user-images.githubusercontent.com/38302725/48050096-044a1080-e1f5-11e8-9105-a845cc905a99.png">

<img width="1026" alt="internal_error" src="https://user-images.githubusercontent.com/38302725/48050212-5723c800-e1f5-11e8-99c4-ff970579d123.png">
@yuriyz, do we need 2 error descriptions?

**Comment by yuriyz** [comment]
@natt-tester it is bug in serializer. I will check it.

**Comment by yuriyz** [comment]
@natt-tester Fixed, please validate.
