### ISSUE TITLE
Bug : Swagger client returns relative timestamps instead of number of seconds since January 1 1970 UTC

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#228]
Swagger show the example of response for the /introspect-access-token with fields below:
"exp": 299, it is relative time, but IMO it should return absolute timestamp.

It should return Integer timestamp, measured in the number of seconds since January 1 1970 UTC.

See : https://tools.ietf.org/html/rfc7662#section-2.2

Please cover it with test based on swagger client. It should check:

- exp
- iat
- nbf (if present in response)

**Comment by shoebkhan09** [comment]
@yuriyz , could you please elaborate (check nbf (if present in response) ? Should I check for null or a valid date ?

**Comment by yuriyz** [comment]
@shoebkhan09 check for null.

**Comment by shoebkhan09** [comment]
👍

**Comment by shoebkhan09** [comment]
@yuriyz , the spec also talks about another optional parameter, jti.  Should we also add it ?

**Comment by yuriyz** [comment]
@shoebkhan09 yes, please

**Comment by altexy** [comment]
@yuriyz 
https://app.swaggerhub.com/apis/yuriyz1/oxd-server/4.0.0#/developers/introspect-access-token
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/GluuFederation/oxd/version_3.1.3/oxd-https-extension/src/main/resources/swagger.yaml#/developers/introspect-access-token
example value are still confusing, take a look at `exp` response's field

**Comment by yuriyz** [comment]
@altexy example looks correct, you refered `version_3.1.4` instead of `version_4.0.0`, here are correct links
- https://github.com/GluuFederation/oxd/blob/version_4.0.0/oxd-server/src/main/resources/swagger.yaml#L213
- http://petstore.swagger.io/?url=https://raw.githubusercontent.com/GluuFederation/oxd/version_4.0.0/oxd-server/src/main/resources/swagger.yaml#/developers/introspect-access-token

About `https://app.swaggerhub.com/apis/yuriyz1/oxd-server/4.0.0#/developers/introspect-access-token`, I'm updating it from time to time, so it can be outdated. Please always refer to latest source in git (first link above). If you need regenerate client, just take it from git and put into your swaggerhub profile.

**Comment by shoebkhan09** [comment]
Is it fine to close this issue ?

**Comment by yuriyz** [comment]
Fixed as confirmed by @ldeveloperl1985 .
