### ISSUE TITLE
Remove server_name from oxd-conf.json

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#240]
We need to remove `server_name` from `oxd-conf.json`.

Right now when admin installs oxd-server and will try to start it, it will fails because `server_name` is required in the configuration file. This property was added to easier identify different oxd server by human on ecommerce. However now we dropped licensing, so there is no good reason to fail oxd-server start for property which is not used anymore.

**Comment by yuriyz** [comment]
done

**Comment by natt-tester** [comment]
It's done in all the packages:
<img width="764" alt="oxd-conf-json" src="https://user-images.githubusercontent.com/38302725/46995005-8e590900-d162-11e8-91f8-1014e3d0aa3f.png">
