### ISSUE TITLE
Create upgrade script which should upgrade old oxd (2.x, 3.x) to 4.0

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#255]
We need: 

- Create upgrade script which should upgrade old oxd (2.x, 3.x) to 4.0 (it can be placed under `https://github.com/GluuFederation/oxd/tree/version_4.0.beta/upgrade`).
- Create `Upgrade` doc page (same as for CE) which should cover all details (in `version_4.0` branch, https://github.com/GluuFederation/docs-oxd-prod).

Please read wiki page about oxd 4.0 https://github.com/GluuFederation/oxd/wiki/oxd-4.0

In 2.x, 3.x versions we used `oxd-conf.json`, `oxd-default-site-config.json` and `log4j.xml` configuration files.
In 4.x we have everything in one single file `oxd-server.yml` file. Upgrade should create yml file by merging json and xml files. (All license related configuration must be removed, we don't use it anymore since 3.1.4 version).

Data migration: 
oxd have built-in migration of the data. In old versions up to `3.1.1` data was persisted into multiple json files. Since `3.1.1` we persist data into database (h2 or redis). Default is h2. If point in configuration file property to json files `migration_source_folder_path: '/path/to/json/files'` oxd will migrate json files into database.

**Comment by mbaser** [comment]
Implemented
