### ISSUE TITLE
Add access_token as jwt client registration parameters to register_site and update_site commands

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#259]
Add access_token as jwt client registration parameters to register_site and update_site commands

**Comment by yuriyz** [comment]
done in 4.0.beta

**Comment by willow9886** [comment]
does it need to get passed along to @shoebkhan09 for inclusion in swagger?

**Comment by yuriyz** [comment]
@willow9886 I've included it already in swagger spec. See https://github.com/GluuFederation/oxd/blob/2979a97ef1c016622ff8c3bb6785c3da780c9cc3/oxd-server/src/main/resources/swagger.yaml#L326

**Comment by yuriyz** [comment]
@willow9886 https://github.com/GluuFederation/oxd/issues/262
