### ISSUE TITLE
Add command to proxy jwks

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#260]
Add command to proxy jwks. oxd should call `jwks_uri` from discovery response (e.g.  https://ce-dev3.gluu.org/.well-known/openid-configuration) and simply return response without any modification as response of the command.

**Comment by yuriyz** [comment]
Command should accept:

- op_host - REQUIRED
- op_discovery_path - OPTIONAL

It should return response from OP without any modifications.

**Comment by shoebkhan09** [comment]
Done

**Comment by altexy** [comment]
@yuriyz Why we should specify `op_host`, but not `oxd_id` as we do for almost all APIs?
IMO It looks inconsistent.

**Comment by yuriyz** [comment]
@altexy because we don't need oxd entity (`oxd_id`) to fetch jwks. Same as with `/get-client-token` where you don't provide `oxd_id` (using `op_host`).

**Comment by ldeveloperl1985** [comment]
@yuriyz , why are you sending keys as string in response?. 
```
{
    "jwks": "{\"keys\":[{\"kid\":\"3680a688-1ba8-4c3f-9807-a6fdd8409e9b\",\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"exp\":1570719578823,\"crv\":null,\"x5c\":[\"MIIDBDCCAeygAwIBAgIhAOEgsIJ5CCN8Z2rcrZURdUVLGoiC7qGLOJlKdR9vIdueMA0GCSqGSIb3DQEBCwUAMCExHzAdBgNVBAMMFm94QXV0aC
.............
}
```

IMO, it will be good to return with `keys` object in json format(same as op server response) and remove extra `jwks` key.

**Comment by yuriyz** [comment]
@shoebkhan09 please return it as json, not as string.

**Comment by yuriyz** [comment]
done in https://github.com/GluuFederation/oxd/pull/284

@ldeveloperl1985 please check whether all works as expected for GG now.
