### ISSUE TITLE
Change string for invalid oxd_id error

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#266]
Change the description to "Invalid oxd_id. Unable to find **the** site for oxd_id. It does not exist or **has been** removed from the server. Please use **the** register_site command to register a site."

![image](https://user-images.githubusercontent.com/38302725/48749410-c1ffe500-ec72-11e8-8092-9445459b2186.png)

**Comment by yuriyz** [comment]
Fixed by https://github.com/GluuFederation/oxd/pull/301
