### ISSUE TITLE
/healthcheck response should be JSON

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#267]
Please check the response type for the /healthcheck call:

![image](https://user-images.githubusercontent.com/38302725/48755945-229d1b00-ec8f-11e8-9783-d9823b049b9d.png)

It should be a JSON and maybe give the status like [here](https://www.baeldung.com/spring-boot-actuators) using spring boot?
<img width="874" alt="content_type" src="https://user-images.githubusercontent.com/38302725/48756125-ba026e00-ec8f-11e8-8790-e675ff997601.png">

**Comment by yuriyz** [comment]
@shoebkhan09 it seems to be resolved but would you please double check it with swagger-ui ? If swagger-ui does not complain then please close this ticket.
