### ISSUE TITLE
Remove 'set' in string when java not present

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#268]
Please remove the first 'set':

<img width="739" alt="set" src="https://user-images.githubusercontent.com/38302725/48836600-15f5f100-ed7b-11e8-9132-43d6dd4301e7.png">

**Comment by nikdavnik** [comment]
Fixed in github. Will be available in next build.

**Comment by yuriyz** [comment]
Fixed by @nikdavnik . Closing.
