### ISSUE TITLE
Changing default logging level in oxd-server.yml causes errors

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#271]
Steps:

1. Install oxd-server 4.0beta
2. Edit the yml file (added only https://ce-dev6.gluu.org as op_host)
3. Start oxd (success)
4. netstat -tulpn if it actually worked (yes)
5. Stop oxd
6. netstat -tulpn if it actually worked (yes)
7. Change the default logging level to TRACE and save
8. Start oxd

Expected: oxd starts and netstat -tulpn confirms it.
Actual: oxd doesn't start and netstat -tulpn confirms it. Changing the line to any logging level triggers errors:
```
root@osboxes:/home/osboxes# vim /opt/oxd-server/conf/oxd-server.yml
root@osboxes:/home/osboxes# /etc/init.d/oxd-server-4.0.beta start
Starting oxd-server-4.0.beta:
Some errors encountered...
Exiting...
```
[oxd-server.log.tar.gz](https://github.com/GluuFederation/oxd/files/2615376/oxd-server.log.tar.gz)

**Comment by shoebkhan09** [comment]
It seems, the initialization script (oxd-server-4.0.beta.init.d), to figure out the server's running status, looks into logs for this specific string: **o.e.j.s.Server -  Started**

However, when the default logging level in oxd-server.yml,  is changed from INFO to TRACE,DEBUG, WARN, etc. generated log file doesn't contain a string exactly like that. So, the init script considers server as NOT running.

Also when init script discovers any "Error" string in the logs, whether or not it affects the actual working of oxd server, it reports that as an error (this could generally happen when logging is lower than INFO, like DEBUG/TRACE), and terminates the actually Running oxd-server with "Some errors encountered message".

I think init script can be coded such that, if the logging level is not INFO, then it should bypass the check for server's running status.

**Comment by natt-tester** [comment]
@ganesh-at-wiw, @nikdavnik, can you take a look at this? We need a fix.

**Comment by shoebkhan09** [comment]
@yuriyz , as you suggested if we drop the default log level from oxd-server.yml, we may not need any plumbing with the init script. Otherwise the script may fail to recognize the actual status of server if for any reason log messages are altered in case log level get changed.

**Comment by yuriyz** [comment]
@shoebkhan09 right, so far it sounds as best approach.

**Comment by yuriyz** [comment]
@natt-tester root logger conf is removed from config file in this way preventing user from changing it.
