### ISSUE TITLE
Improve log message if certificate is not imported

### ISSUE THREAD

**Issue by shoebkhan09** [GluuFederation/oxd#272]
Client registration fails if certificate on client side, required for handshake,  is not imported.

**Comment by yuriyz** [comment]
oxauth caught network exception and does not allow oxd to handle it. First I will it on oxauth-client side (within this ticket https://github.com/GluuFederation/oxAuth/issues/954) in 3.1.5, then we should switch oxd 4.0.beta to oxauth 3.1.5 (from current 3.1.4) and only then handle exception correctly with clear message for user.

**Comment by yuriyz** [comment]
Now we propagate IOException in oxauth-client since 3.1.5
https://github.com/GluuFederation/oxAuth/commit/e8ccee87fc75fe435faa969aacd50431c268f7cb

**Comment by yuriyz** [comment]
fixed in 4.0.
