### ISSUE TITLE
UnknownHostException at get-client-token call

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#274]
Steps:

1. Install oxd 4.0beta in a Ubuntu 14 vm
2. Change the op_host to https://ce-dev6.gluu.org in the yml config file
3. Start the oxd server (success)
4. Power off the machine
5. Check the oxd server status **(DOWN -- shouldn't it be added to autostart?)**
6. Start the oxd server
7. Make a get-client-token call

Expected: The call is successful (200).
**Actual: There's an error:** 

`"error": "no_connect_discovery_response",
    "error_description": "Unable to fetch Connect discovery response /.well-known/openid-configuration"`

**The log shows that instead of the blank value for op_discovery_path, the oxd server takes the name of the parameter:**
 
```
ERROR  [08:18:20.478] [dw-19 - POST /get-client-token] o.x.o.c.OpenIdConfigurationClient -  ce-dev6.gluu.orgop_discovery_path: Name or service not known
```
[oxd-server(1).log](https://github.com/GluuFederation/oxd/files/2618998/oxd-server.1.log)

**Comment by MohitMaliFtechiz** [comment]
Hi @natt-tester , this could be possibly you forget to set 'op_discovery_path' . Let me quote from documentation 

"Path to the OpenID Connect Provider's discovery document. For example, if it is https://example.com/.well-known/openid-configuration then the path is blank . But if it is https://example.com/oxauth/.well-known/openid-configuration then the path is /oxauth ".

 please retest the issue with set op_discovery_path='/oxauth'.  let me know if its works

**Comment by duttarnab** [comment]
I followed the mentioned steps using https://ce-dev6.gluu.org as AS. I noticed following 2 things.

1. The oxd -server was automatically started after the machine was restarted.
2. After the machine was restarted the get-client-token call was successful (200) and returned `access_token`.
This issue seems to be already resolved on oxd.

**Comment by duttarnab** [comment]
I am closing this issue as it is not reproducible in oxd-4.0.
