### ISSUE TITLE
lsox scipt with non-human readable names

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#275]
In oxd-server 3.1.4 we had nulls given as client names whenever the user didn't specify any client name during a setup-client call. In 4.0beta, the log displays the name as empty:

<img width="460" alt="obraz" src="https://user-images.githubusercontent.com/38302725/49127574-f67f3b00-f31b-11e8-80a8-dc13024c577b.png">

**Should we display this property as empty?**

**Comment by yuriyz** [comment]
It looks good to me.

**Comment by natt-tester** [comment]
@yuriyz if we're going with it in 4.0, please close the issue.
