### ISSUE TITLE
Change string for invalid scope_expression

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#277]
Please fix the marked typo and change the string to the following:

**“The scope expression is invalid. Please check the documentation and make sure it is a valid JsonLogic expression.”**

<img width="776" alt="scope_expression" src="https://user-images.githubusercontent.com/38302725/49137047-77036300-f33f-11e8-9015-9bb88686a1bd.png">

**Comment by yuriyz** [comment]
Fixed within https://github.com/GluuFederation/oxd/pull/278
