### ISSUE TITLE
lsox script with oxd_id parameter + valid token throws NPE

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#282]
Might be related to #280 

Steps:

1. In a fresh installation **with running oxd**, make a register-site call:
```
curl -X POST -k \
  https://localhost:8443/register-site \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 33917b1a-f7ae-4afb-9be4-bd9fdd631621' \
  -H 'cache-control: no-cache' \
  -d '{
  "authorization_redirect_uri": "https://client.example.org/cb",
  "redirect_uris": [
    "https://client.example.org/cb"
  ],
  "post_logout_redirect_uri": "https://client.example.org/cb",
  "client_token_endpoint_auth_method": "client_token_endpoint_auth_method",
  "scope": [
    "openid", "oxd", "uma_protection"
  ],
  "trusted_client": true,
  "op_host": "https://ce-dev3.gluu.org",
  "client_secret": "client_secret"
}'
```
2. Go to /opt/oxd-server/bin
3. Enter `sh lsox.sh -oxd_id {valid oxd_id} -a {valid token from the register-site call}`
4. Press Enter

Expected: The details of the given oxd_id should be displayed.
Actual: There's an Internal Server Error (500) displayed with a NPE in the logs (the last lines):

[oxd-server.log](https://github.com/GluuFederation/oxd/files/2627548/oxd-server.log)

**Comment by yuriyz** [comment]
Fixed NPE which was caused by issue during deserialization of `GetRpParams`
