### ISSUE TITLE
Missed OP discovery info to implement OpenID Connect GG plugin

### ISSUE THREAD

**Issue by altexy** [GluuFederation/oxd#291]
I'm working on OpenID Connect GG plugin.

We use oxd as middleware between GG and GS, never talk to GS directly.

IMO we miss (at least) next information returned by OpenID Connect discovery endpoint:
- issuer
- id_token_signing_alg_values_supported

Any ideas?

**Comment by yuriyz** [comment]
We already proxy `jwks_uri` static page via oxd. If required we introduce `discovery` command to proxy also connect static configuration.

**Comment by altexy** [comment]
@yuriyz 

> We already proxy `jwks_uri` static page via oxd. If required we can introduce `discovery` command to proxy also connect static configuration.

`jwks_uri` is not static, keys are rotated every some days.

Discovery information is more static but may be changed any time by OP admin.
So I would prefer to know that every time I call `discovery` command I get fresh info from OP.

All kind of caching I will implement at GG side.

**Comment by yuriyz** [comment]
Fixed within https://github.com/GluuFederation/oxd/pull/316
