### ISSUE TITLE
Return id_token's claims as is in id_token_claims

### ISSUE THREAD

**Issue by altexy** [GluuFederation/oxd#305]
I’m dealing with /get_tokens_by_code endpoint.
It returns id_token’s claims in id_token_claims field.
But the format is very strange - every claim is an array.

We need to return claims in the same format as within JWT payload.

**Comment by ldeveloperl1985** [comment]
Please return time fields `"exp", "iat", "auth_time"` in integer not in string. Also please possible then take this issue in priority because we need it for testing GG plugins.

**Comment by MohitMaliFtechiz** [comment]
@ldeveloperl1985 we are getting response like {“active”:true,”scope”:
Response:
[“openid”,”oxd”],”client_id”:”@!DBE5.84F8.631A.9172!0001!CD07.49BE!0008!B3E5.12AE.539F.7530”,”username”:null,”token_type”:”bearer”,”exp”:1552918091,”iat”:1552917791,”sub”:””,”aud”:”@!DBE5.84F8.631A.9172!0001!CD07.49BE!0008!B3E5.12AE.539F.7530”,”iss”:”https://ce-dev3.gluu.org","jti":null,"acr_values":null}

Please let us know why is auth_time required?

**Comment by altexy** [comment]
@MohitMaliFtechiz Do you mix up `/get-client-token` and `/get-tokens-by-code` endpoint?

Example response from Swagger:
```JSON
{
  "access_token": "b75434ff-f465-4b70-92e4-b7ba6b6c58f2",
  "expires_in": 299,
  "id_token": "eyJraWQiOiI5MTUyNTU1Ni04YmIwLTQ2MzYtYTFhYy05ZGVlNjlhMDBmYWUiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJp",
  "refresh_token": "33d7988e-6ffb-4fe5-8c2a-0e158691d446",
  "id_token_claims": {
    "at_hash": [
      "Cx2dz5Wvw_kBXAcTs3mFA"
    ],
    "aud": [
      "l238j323ds-23ij4"
    ],
    "sub": [
      "jblack"
    ],
    "auth_time": [
      "string"
    ],
    "iss": [
      "https://as.gluu.org/"
    ],
    "exp": [
      "string"
    ],
    "iat": [
      "string"
    ],
    "nonce": [
      "string"
    ],
    "oxOpenIDConnectVersion": [
      "string"
    ]
  }
}
```

**Comment by MohitMaliFtechiz** [comment]
I have made commit for this https://github.com/GluuFederation/oxd/issues/305 ,  please check and let me know if anything else needed to changed.

**Comment by yuriyz** [comment]
done in version_4.0
