### ISSUE TITLE
NEW : Swagger spec must reflect error json returned by oxd 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#307]
oxd returns error as json but swagger spec does not reflect it. Also it must be covered by test.

**Comment by duttarnab** [comment]
I have found that ModelMapping feature has not yet introduced in ApiException.java. Please refer below ticket for details
 
https://github.com/swagger-api/swagger-codegen/issues/2602

**Comment by yuriyz** [comment]
@duttarnab you are right, it doesn't put error response model correctly. But anyway lets add model and declare it everywhere, so we have everything ready. Also for client code it's not big problem to convert string into object when model class is already there.

Here I've added error model description :
https://github.com/GluuFederation/oxd/commit/6708f587ac6c46f7d7f8e22f1e26d4731cc528d6

Please open PR which use that model in all error responses. Example:
```
        400:
          description: Invalid parameters are provided to endpoint.
          schema:
            $ref: '#/definitions/ErrorResponse'
```

**Comment by yuriyz** [comment]
Fixed by https://github.com/GluuFederation/oxd/pull/313
