### ISSUE TITLE
oxd-4.0: Remove redundant  Logger-specific levels (`Trace`) from oxd-server.yml

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#332]
**Steps:** 

1. Open oxd/oxd-server/src/main/resources/oxd-server.yml of oxd-4.0
2. Check Line# 42 and 43. Loggers `org.gluu: TRACE` is repeated 2 times in file

Expected: There should be only one `org.gluu: TRACE`.

**Comment by yuriyz** [comment]
Fixed by https://github.com/GluuFederation/oxd/pull/333
