### ISSUE TITLE
Update oxd - 4.0 documentation with latest changes done

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#340]
Update oxd - 4.0 documentation with latest changes done.

OXD docs link: https://gluu.org/docs/oxd/4.0/tutorial/

**Comment by duttarnab** [comment]
Done in #49

**Comment by duttarnab** [comment]
https://gluu.org/docs/oxd/4.0/api/ - /introspect-access-token, /get-jwks docs are missing

they exist in API section, but not in navigator on the right side

**Comment by duttarnab** [comment]
**Changes Done**
1. Corrected java tutorial to use oxd in sample java web application
2. Corrected Links in Python tutorial

**Comment by willow9886** [comment]
Closing.
