### ISSUE TITLE
Unify parameters between /register-site and /update-site

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#354]
Add missed parameters from `/register-site` to `/update-site`. If something is missed in oxauth-client-s `RegisterRequest` please collect it  and post info to this ticket.

**Comment by ldeveloperl1985** [comment]
After updating the client using OXD `update-site` it removes some configs which I configured on `register-site` time. I've register client with `rpt_as_jwt: true`, `access_token_as_jwt: true` but after just `claims_redirect_uri` update, it set this properties to `false`. 

Please check OXD log  [oxd-server.log](https://github.com/GluuFederation/oxd/files/3436296/oxd-server.log)

**Comment by duttarnab** [comment]
> Add missed parameters from `/register-site` to `/update-site`. If something is missed in oxauth-client-s `RegisterRequest` please collect it and post info to this ticket.

I have found below parameters present in `/register-site` but not in `/update-site`. Working to  Add below params in `/update-site`.

    
    client_registration_access_token
    client_registration_client_uri
    client_name
    client_token_endpoint_auth_signing_alg
    trusted_client
    logo_uri
    client_uri
    policy_uri
    front_channel_logout_session_required
    tos_uri
    jwks
    id_token_binding_cnf
    tls_client_auth_subject_dn
    subject_type
    run_introspection_script_beforeaccess_token_as_jwt_creation_and_include_claims
    id_token_signed_response_alg
    id_token_encrypted_response_alg
    id_token_encrypted_response_enc
    user_info_signed_response_alg
    user_info_encrypted_response_alg
    user_info_encrypted_response_enc
    request_object_signing_alg
    request_object_encryption_alg
    request_object_encryption_enc
    default_max_age
    require_auth_time
    initiate_login_uri
    authorized_origins
    access_token_lifetime
    software_id
    software_version
    software_statement
    custom_attributes

**Comment by duttarnab** [comment]
@yuriyz , I can see following 2 params in https://github.com/GluuFederation/oxAuth/blob/version_4.0.b1/Client/src/main/java/org/gluu/oxauth/client/RegisterRequest.java. 

These params are present in https://github.com/GluuFederation/oxd/blob/version_4.0/oxd-common/src/main/java/org/gluu/oxd/common/params/RegisterSiteParams.java class.

Kindly confirm if we need to add these in this

**Comment by yuriyz** [comment]
Right, we definitely don't need them as well as client_registration_access_token.

**Comment by duttarnab** [comment]
> After updating the client using OXD `update-site` it removes some configs which I configured on `register-site` time. I've register client with `rpt_as_jwt: true`, `access_token_as_jwt: true` but after just `claims_redirect_uri` update, it set this properties to `false`.
> 
> Please check OXD log [oxd-server.log](https://github.com/GluuFederation/oxd/files/3436296/oxd-server.log)

We have fixed below params showing above issue. 

```
access_token_signing_alg
access_token_as_jwt
rpt_as_jwt
front_channel_logout_session_required
```

**Comment by duttarnab** [comment]
Fixed by 
https://github.com/GluuFederation/oxd/pull/357
https://github.com/GluuFederation/oxd/pull/357
