### ISSUE TITLE
Create stress/load test which should cover all APIs with mocked OP

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#360]
Create stress/load test which should cover all APIs with mocked OP.

Right now OP can process ~100req/s. Last time I've stressed oxd, it had similar performance which obviously was due to OP. It would be nice to mock OP and then stress tests against mocked OP. In this case we can see real numbers of oxd code (without limit that comes from OP).

**Comment by duttarnab** [comment]
Do we need to load test using tools like jmeter and mock OP mockito?

**Comment by yuriyz** [comment]
Yes to both. 
1. Basically we have to isolate `oxauth-client` client's creations. E.g. via `OpClientFactory` which should create `TokenClient/UserInfoClient/RegisterClient etc.`. And then just mock them during tests run. It should be isolated by guice under `test`. 
2. Prepare 2 jmeter scripts to run Authorization Code Flow and UMA protection use cases.

**Comment by duttarnab** [comment]
Closed by https://github.com/GluuFederation/oxd/pull/365
