### ISSUE TITLE
We need `scopes` explicitly passed into `/uma-rs-check-access` to have granular access handling

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#362]
We need `scopes` explicitly passed into `/uma-rs-check-access` to have granular access handling. Right now we register ticket for all scopes.

**Comment by duttarnab** [comment]
We are already passing `path` and `http_method` as request parameters which enables oxd to select `scopes` of a particular resource_id. Hence, ticket is registered for only those `scopes` (if access is denied). I think  `path` and `http_method` already selecting scopes of a particular resource_id so we need not pass explicitly. 

@yuriyz, please confirm in the case the above understanding is incorrect.

**Comment by yuriyz** [comment]
That is the purpose of this ticket. Idea is to specify scopes in parameters to command. We should be able so say explicitly which exactly scope to check.

Lets say we have 
```
            {
                "path":"/photo",
                "conditions":[                   
                    {
                        "httpMethods":["PUT", "POST"],
                        "scopes":[
                            "all",
                            "add",
                            "view",
                        ],
                        "ticketScopes":[
                            "add"
                        ]
                    }
                ]
            }
```

If we check access for `POST` with `/photo` oxd iterates over all scopes and register ticket for `add`. If we want to check and register ticket for `view` currently we don't have way to do that. Note: it's important to validate passed scopes against resource scopes (`resources.getScopes().contains(params.getScopes())`).

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/407
and
https://github.com/GluuFederation/docs-oxd-prod/pull/80
