### ISSUE TITLE
Introduce new `/uma-rs-modify` command to be able modify existing resource

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#363]
Introduce new `/uma-rs-modify` command to be able modify existing resource. It should be possible modify resource by `path` and `http method`.

**Comment by duttarnab** [comment]
We already have `overwrite` param in `/uma-rs-protect` command, when set to `true` means remove existing UMA Resource and register new based on JSON Document. Please confirm if we can take this feature as an alternative to this ticket.

**Comment by yuriyz** [comment]
Idea is to modify particular resource, not whole set. If we have huge JSON document then we need to re-add each resource, if there are thousands then it's redundant load on server while we can tune just the one which we really need.

We need:
- `registrar.getResourceSetId(path, method)` to get resource id
- `org.gluu.oxauth.client.uma.UmaResourceService#updateResource` to modify particular resource by id.

`/uma-rs-modify` params:
- oxd_id
- path
- method
- scopes
- scopeExpression
- name

Operation should first call AS and if it's successful update local data in oxd.

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/399,
https://github.com/GluuFederation/oxd/pull/406,
https://github.com/GluuFederation/docs-oxd-prod/pull/76
