### ISSUE TITLE
Use cached mocked objects in OpClientFactoryMockImpl.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#374]
Lets create mocked objects and re-used them because profiler is spammed with a lot of blocks produced by mockito.

![image](https://user-images.githubusercontent.com/2013070/65780027-89158400-e151-11e9-9830-dcc8a9128d9d.png)

**Comment by duttarnab** [comment]
@yuriyz, which cpu profiler you are using?

**Comment by yuriyz** [comment]
@duttarnab yourkit

**Comment by duttarnab** [comment]
Done in 4.2
