### ISSUE TITLE
Rhel-7 package of oxd Does not purge the oxd db at /opt/oxd-server/data

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#378]
Rhel-7 package of oxd Does not purge the oxd db at /opt/oxd-server/data on execution of uninstall command.

https://docs.google.com/spreadsheets/d/1S4pfCTezexVzk_0-2N9MzfI81p11hf5cAfzKyGVl-jk/edit#gid=2107314502

![image](https://user-images.githubusercontent.com/32794267/66020246-23841780-e504-11e9-94af-38be91962ed7.png)

**Comment by yuriyz** [comment]
@nikdavnik would you please check?

**Comment by yuriyz** [comment]
@duttarnab Davit said that it's fixed and re-packaged. Please validate.
