### ISSUE TITLE
Incorrect scopes are added when client is updated using `/update-site` command

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#379]
Steps:
------

1. Configure CE with 'openid', 'profile', 'email', 'address', 'read' scopes enabled for dynamic registration.

2. Register new client using oxd with scope: 'openid', 'profile', 'email'. The client registered in CE will have 'openid', 'profile', 'email' scope .

3. Now using `/update-site` command update any other field of client (not scope). 

4. You should see all scopes enabled for dynamic registration added to the update client which is incorrect. (i.e.  'openid', 'profile', 'email', 'address', 'read')

**Comment by yuriyz** [comment]
Done.
