### ISSUE TITLE
Refactor `/register-site` operation code

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#381]
For registering client using oxd the steps should be

1. Get request parameters object, validate params and set it with fallback.
2. Create request object which will be posted to op_host.
3. If successful then fill in Relying Party (RP) object from params and save it in oxd database.

create separate mapper and cover it with tests to fill RP object with RegisterRequest object and reconstruct RegisterRequest using RP.

**Comment by yuriyz** [comment]
done
