### ISSUE TITLE
Remove ability to set/update Pre-Authorization flag from oxd 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#384]
Remove from /update-site and /register-site `Pre-Authorizaton` and whether to persist authorizations or not.

Remove:
- from parameters `setTrustedClient`
- filter it out when we pass it as custom attribute (`oxAuthTrustedClient`)
Please add test to make sure it's filtered out.

https://support.gluu.org/7616/

Mike:
Whether to persist client authorizations is a preference of the OP. The client should not get a say in this. You'll have to use the oxTrust config API's if you want to automate this. If this method exists in oxd, I'm going to talk to the developers about removing it.

6:48 PM
I also hope that the client can’t set the preAuthorization flag

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/docs-oxd-prod/pull/81
and
https://github.com/GluuFederation/oxd/pull/408
