### ISSUE TITLE
Make h2 database username/password connection details configurable in yml file

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#388]
Make h2 database username/password connection details configurable in yml file. Please update docs accordingly.

**Comment by duttarnab** [comment]
After setting `username/password` of h2 db once,  if user changes `username/password` of h2 db in yml file then should oxd update `username/password` for database or it  should `incorrect username/password`.

**Comment by yuriyz** [comment]
For first time it created db if it does not exist. If after creation credentials are changed then we should show `incorrect username or password` error.

**Comment by duttarnab** [comment]
Done by https://github.com/GluuFederation/oxd/pull/394 and https://github.com/GluuFederation/docs-oxd-prod/pull/74
