### ISSUE TITLE
Sync client from OP : Update oxd database by reading client

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#390]
oxd persists clients information in own persistence. If admin goes to OP directly (oxtrust) and change client data directly then oxd will not know about it and can act on outdated data. It produce a lot of confusion. I've added explicit note to oxd docs to make it clear that oxd clients should be updated via oxd however I think we can do better here. OP allows to read client information. By default we do not sync client data because we don't want to load OP with redundant calls. However if customer really wants it, he/she can enable it for given client.

Add to `/register-site` and `/update-site` (and Rp object):

- `sync_client_from_op: false` - whether to sync client from OP
- `sync_client_period: 86 400` - in seconds, defaults to 1 day.

oxd should sync client only when needed (when client is used by oxd operation, no periodic syncing!).

Snippet from docs
```
oxd saves data in own persistence (`h2`, `redis`) and acts as RP for OP. Therefore if client is created by oxd on OP side it is highly recommended to update client's data via oxd API. Otherwise if change client's data by configuring OP directly then data in oxd persistence can be outdated which can lead to confusion and unexpected behavior.
````

Implementation details
1. Add RpSyncService and RpSyncServiceTest (create PR1 with just these 2 classes and changes in Rp class)

```
public class RpSyncService {

    public static boolean shouldSync(Rp rp) {  <--- we should have tests for each case here ˜5-6 test at least
        if (rp == null || !rp.isSyncClientFromRp())
            return false;
        if ((rp.getLastSynced() + rp.getSyncClientPeriod() * 1000) < new Date().getTime())
            return true;            
        return false;
    }

    public Rp getRp(String oxdId) {
        Rp rp = rpService.getRp(oxdId);
        if (!shouldSync(rp)) 
            return;
   
        return sync(rp);
    }

    private void sync(Rp rp) {
        if (!shouldSync(rp)) 
            return;
      
        // read client with oxauth-client and update Rp object
        return rp;
    }
}

```
2. Add to Rp 
- `last_synced: date`
- `sync_client_from_op: boolean`
- `sync_client_period: integer - number of seconds`

3. create separate PR2 with usages changes (replace RpService.getRp() with RpSyncService.getRp() in operations, make `RpService.getRp()` private) and make changes for `/register-site` and `/update-site` with tests.

**Comment by duttarnab** [comment]
` public static boolean shouldSync(Rp rp) {  <--- we should have tests for each case here ˜5-6 test at least`

@yuriyz could you please mention the cases for which we need write tests. 

One I could think of is: 
Register a client--> bring client info from op--> persist op client info to oxd if difference is found or else do not sync--> check if persistence  is successful.

**Comment by yuriyz** [comment]
@duttarnab each case that can be run inside method: 
- rp null 
- rp not null;
- isSyncClientFromRp true 
- isSyncClientFromRp false
- getLastSynced set
- getLastSynced not set
- getSyncClientPeriod value

**Comment by yuriyz** [comment]
@duttarnab After #395 merge the last piece is:
1. make private `org.gluu.oxd.server.service.RpService#getRp`
2. use `org.gluu.oxd.server.service.RpSyncService#getRp` everywhere in code.

**Comment by duttarnab** [comment]
Done using 
https://github.com/GluuFederation/oxd/pull/395,
https://github.com/GluuFederation/oxd/pull/398,
https://github.com/GluuFederation/docs-oxd-prod/pull/75
