### ISSUE TITLE
Add spontaneous scopes to oxd

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#409]
1. To `/register-site` and `/update-site` add
- `allow_spontaneous_scopes` - boolean, whether to allow spontaneous scopes for client
- `spontaneous_scopes` - list of spontaneous scopes (regexp against which validation is performed)

2. Replicate oxauth client spontaneous test for oxd. For both Connect and UMA.
https://github.com/GluuFederation/oxAuth/blob/6e420f60a298334b13b62246ff0dba278c640de7/Client/src/test/java/org/gluu/oxauth/ws/rs/SpontaneousScopeHttpTest.java

https://github.com/GluuFederation/oxAuth/blob/d2edeab74d96325d22b82ea56c432463545fc967/Client/src/test/java/org/gluu/oxauth/ws/rs/uma/UmaSpontaneousScopeHttpTest.java

Connect docs: https://github.com/GluuFederation/docs-ce-prod/commit/45011ef5d13911b1c37fde0f31994b54b8c3ac3f

UMA docs: https://github.com/GluuFederation/docs-ce-prod/commit/817d50f3c5d76b26966a36a962cb050e1d2a3337

**Comment by duttarnab** [comment]
PR https://github.com/GluuFederation/oxd/pull/413 raised addressing point#2 of this ticket.

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/411 and https://github.com/GluuFederation/oxd/pull/413
