### ISSUE TITLE
Add HD to authorization request

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#42]
the [hd param](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) can be added to a Google OpenID Connect authorization request to provide a hint that this user is a member of a partiuclar hosted domain. Perhaps addtitional _ad hoc_  request params can be specified somewhere in the config.

**Comment by yuriyz** [comment]
@nynymike sure,  I can pass it to oxauth. It needs to be correctly handled by oxauth Authorization Endpoint. Do we have corresponding issue in oxauth ? If yes, please provide link so I can take over otherwise I will create it.

**Comment by yuriyz** [comment]
@nynymike created https://github.com/GluuFederation/oxAuth/issues/321

**Comment by nynymike** [comment]
oxAuth won't support this.  It's just a feature if the person is using oxd with Google as the OP.

**Comment by yuriyz** [comment]
@nynymike done
