### ISSUE TITLE
Fix oxd after httpclient upgrade in oxauth

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#423]
Failed build:
https://ox.gluu.org/jenkins/job/oxD_4.2/161/console

It failed due to httpclient upgrade : https://github.com/GluuFederation/gluu-core-bom/commit/92e8630c8f413fd535f21d6c21575bc18337e28d

Update oxd code according to new http client.

Sample fixes in oxauth:
https://github.com/GluuFederation/oxAuth/commit/5fe407483aa343b4b21e2f31521eacd825de1bb4
https://github.com/GluuFederation/oxAuth/commit/c5eeb2f118741afacd5a63c081b71488d96d6bfb

**Comment by duttarnab** [comment]
Done
