### ISSUE TITLE
Pass Connect RP conformance tests

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#437]
oxd has to pass Connect RP conformance tests

See https://openid.net/certification/rp_testing/

Overview: https://openid.net/certification/

Milton (@miltonbo) can help with gathering and sending resources.

**Comment by duttarnab** [comment]
Testing logs for `Authorization code flow` : https://rp.certification.openid.net:8080/log/oxd

**Comment by duttarnab** [comment]
Done in 4.2.2
