### ISSUE TITLE
If 'iat' value is missing from `ID_TOKEN` then `ID_TOKEN` should be rejected during token validation.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#438]
![image](https://user-images.githubusercontent.com/32794267/77569777-c1273500-6ef0-11ea-8fb7-36147cecc608.png)

As per  Connect RP conformance test case if 'iat' value is missing from `ID_TOKEN` then `ID_TOKEN` should be rejected during token validation.

Parent Ticket: https://github.com/GluuFederation/oxd/issues/437

**Comment by duttarnab** [comment]
@yuriyz please suggest if we should implement this validation

**Comment by yuriyz** [comment]
@duttarnab yes, we should do everything that is required to pass certification.

**Comment by duttarnab** [comment]
Done in 4.2
