### ISSUE TITLE
Add border around error logs to highlight the errors

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#458]
Add border around error logs to highlight the errors

**Comment by duttarnab** [comment]
We have done this locally to print the confirmation test error message in the below format. @yuriyz do you think we should commit this in github.

**Comment by yuriyz** [comment]
@duttarnab is it easier for you to read logs with these "borders"? For me it doesn't make much different, maybe because I read logs a lot ). If you find it really useful then feel free to open PR.

**Comment by duttarnab** [comment]
As discussed, it doesn't make much difference to add a border around Error message. It will only done for confirmation tests.
