### ISSUE TITLE
Remove basic in "acr_values":["basic"] from oxd-default-site-config.json and add email in "scope":["openid", "profile", "email"],

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#47]
When I send request by  get_autorization_url pratacol (without acr_value), acr_value get default "acr_value" value from oxd-default-site-config.json.
**I think need to return authorization_url with OP default value or url without acr_values parameter**

{"command":"get_authorization_url","params":{"oxd_id":"db0e5d41-855a-430e-a3c9-06e5faa91962","acr_values":null,"prompt":null,"scope":null}}
{"status":"ok","data":{"authorization_url":"https://ce-dev2.gluu.org/oxauth/seam/resource/restv1/oxauth/authorize?response_type=code&client_id=@!40EA.D454.9D4F.E876!0001!ECE8.BBEF!0008!55EF.A80C&redirect_uri=https://gluu.loc/index.php?option=oxdOpenId&scope=org_name+uma_authorization+profile+imapData+uma_protection+mt_scope+phone+mobile_phone+work_phone+user_name+email+clientinfo+address+openid&state=l2u1kn5njn7ctbefq7ji6rqfim&nonce=itdf5f3irn17evu85rf6vblqj9&acr_values=basic"}}

**I think need to "email" scope too in oxd-default-site-config.json, becouse if OP doesnt support "email" scope that OP we can not use for plugins**

**Comment by yuriyz** [comment]
@dollar007 done https://github.com/GluuFederation/oxd/commit/d0b4f2f59612831df28f6c02e3ea626cf8b97dd4
