### ISSUE TITLE
add new implicit_flow command

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#5]
add new implicit_flow command

**Comment by willow9886** [comment]
@yuriyz does this still make sense to implement?

**Comment by yuriyz** [comment]
@willow9886 yes, we need stateful version of implicit command.

**Comment by nynymike** [comment]
I don't think we should support this... if you want to use the implicit flow, use [openid-implicit-client](https://github.com/GluuFederation/openid-implicit-client)
