### ISSUE TITLE
Provide fallback for all parameters

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#50]
I noticed that the params here:
  https://oxd.gluu.org/docs/oxdserver/#register-site

Do not match the config docs:
  https://oxd.gluu.org/docs/conf#oxd-default-site-configjson

**Comment by duttarnab** [comment]
Do we need to add all request param of `/register-site` operation in `defaultSiteConfig` section (fallback configuration values) of `oxd-server.yml`. Please confirm.

**Comment by yuriyz** [comment]
Yes, correct.

**Comment by yuriyz** [comment]
Done in https://github.com/GluuFederation/oxd/pull/370
