### ISSUE TITLE
Add `bindHost` with default value localhost

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#503]
Mike: I think from a security perspective, you may want to make oxd listen on an internal ethernet interface.

**Comment by yuriyz** [comment]
@mbaser can we have explicit question during installation for it? It should reduce confusion from users.

**Comment by duttarnab** [comment]
@yuriyz , is this ticket is same as https://github.com/GluuFederation/oxd/issues/210.

**Comment by duttarnab** [comment]
PR raised: Here, is how it is working.

**Comment by duttarnab** [comment]
Done in 4.2

**Comment by duttarnab** [comment]
It was suggested to use service address or `hostname` as `bindAddress` along with `ip_address`. It was decided to define a NetworkPolicy ( this is a kubernetes object) that restricts access to oxd . Basically does the same thing as bindAddress but its on the outer layer of the pod. Hence bindAddress here would be set to *.
So there will be no changes at oxd side.

![image](https://user-images.githubusercontent.com/32794267/87225997-98974e00-c3ae-11ea-89ac-03a77de1ccd7.png)
