### ISSUE TITLE
Write test with state=base64urlencode(url)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#538]
Write test with state=base64urlencode(url)

1) by default assume it’s already encoded and declare it in documentation that it has to be encoded (means we don’t encode it by default)
2) add configuration option (with default value false), when admin change it to true encode state value.

**Comment by duttarnab** [comment]
Done in version-4.2.1

**Comment by duttarnab** [comment]
Done in 5.0

**Comment by duttarnab** [comment]
oxd will Encode `state` and  `nonce` is encoding is allowed in oxd-server.yml.

Also implemented in 4.2.2
