### ISSUE TITLE
Automation of swagger client generation in oxd

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#557]
Currently, we generated swagger client manually in oxd. The process can be automated so that client is automatically generated on built if the `swagger.yml` file is modified.

Steps:

1. Add `swagger-codegen-cli.jar` dependency in pom.xml of oxd project.
2. generate client using the below command triggered by maven profile.

java -jar swagger-codegen-cli.jar generate -i swagger.yaml -D hideGenerationTimestamp=true -l java

**Comment by duttarnab** [comment]
@yuriyz, do you think this ticket is useful.

**Comment by yuriyz** [comment]
Yes, I like it. We need the same on `oxauth-config` project. cc @pujavs

**Comment by nynymike** [comment]
yes, this is a great idea

**Comment by duttarnab** [comment]
Done in 5.0.0
