### ISSUE TITLE
Build fails with Return code is: 501 , ReasonPhrase:HTTPS Required.

### ISSUE THREAD

**Issue by elch78** [GluuFederation/oxd#562]
> Downloading from gluu: http://ox.gluu.org/maven/org/gluu/oxauth/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from repository.jboss.org: http://repository.jboss.org/nexus/content/groups/public-jboss/org/gluu/oxauth/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from central: http://repo1.maven.org/maven2/org/gluu/oxauth/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from bouncycastle: http://repo2.maven.org/maven2/org/bouncycastle/org/gluu/oxauth/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from local: file:///home/edn1imb/IdeaProjects/oxd/oxd-common/../oxd-repo/org/gluu/oxauth/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.gluu:oxauth:5.0.0-SNAPSHOT/maven-metadata.xml from/to central (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/gluu/oxauth/5.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 501 , ReasonPhrase:HTTPS Required.
[WARNING] Could not transfer metadata org.gluu:oxauth:5.0.0-SNAPSHOT/maven-metadata.xml from/to bouncycastle (http://repo2.maven.org/maven2/org/bouncycastle): repo2.maven.org

Fix: just use https for repositories.

**Comment by yuriyz** [comment]
@duttarnab lets use https for maven public repo.

**Comment by yuriyz** [comment]
@elch78 thanks for report. Feel free to open PR in future. I see you already made similar commits into your own repo:
https://github.com/elch78/oxd/commit/7e5e553d4a91ec2d62ef26acabfd4d3ce9fa1f7d

**Comment by elch78** [comment]
Same problem in the oxd java example

**Comment by duttarnab** [comment]
Fixed in oxd `java sample` project. https://github.com/GluuFederation/oxd-java-sample
