### ISSUE TITLE
UMA protection for oauth 2 hack

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#57]
https://threatpost.com/oauth-2-0-hack-exposes-1-billion-mobile-apps-to-account-hijacking/121889/

**Comment by yuriyz** [comment]
@duttarnab please check whether it's actual.

**Comment by duttarnab** [comment]
@yuriyz , I found an issue when testing with op_host: `jenkins-ldap.gluu.org`

**Steps:** 

1. Register a client (say `Client-1`) with oxd `/register-site` with `response_types: token`
2. Register another client (say `Client-2`) with oxd `/register-site` with `response_types: token`
3. Using oxd `/get-authorization-url` get authorization url for  `Client-1`
4. Fire  `Client-1` authorization url on browser and get `access_token` 
5. Using `access_token` of `Client-1` you can get user details of `Client 2` (`/get-user-info`)

**Comment by yuriyz** [comment]
UserInfo operation accepts only access_token, thus it represent user info associated with that access_token. It doesn't have client_id to match it. So not sure it's issue in context of Connect.
If there no any other issues I think we can close this ticket.

**Comment by duttarnab** [comment]
Tested again. I could not find any bugs. Closing this ticket.
