### ISSUE TITLE
Update license to check number of oxd clients

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxd#58]
We want to understand how many clients are using each oxd installation.

**Comment by yuriyz** [comment]
Idea is to track oxd clients on the oxd server and pass that information to license server. License server has to expose this info via REST API.

**Comment by yuriyz** [comment]
This task must be done right after License Server start tracking oxd_id https://github.com/GluuFederation/oxLicense/issues/14

**Comment by yuriyz** [comment]
Implemented. Both License Server and oxd are updated.
