### ISSUE TITLE
Support optional PATH for OpenID Connect Discovery

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#59]
It's possible that an OP uses a path to publish it's discovery document. This would be discoverable with WebFinger or through some out-of-band mechanism. 

http://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery
```
The returned Issuer location MUST be a URI RFC 3986 [RFC3986] with 
a scheme component that MUST be https, a host component, and 
optionally, port and path components and no query or fragment components. 
```

**Comment by yuriyz** [comment]
implemented in 3.1
