### ISSUE TITLE
Inapp documentation link not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxd#62]
In-app documentation link is throwing 404. 
![screenshot_2](https://cloud.githubusercontent.com/assets/7156097/21479373/80df742c-cb19-11e6-941b-495c5eb75549.png)

I think we should point documentation link to `https://oxd.gluu.org/docs/2.4.4/plugin/wordpress/` instead of  `https://oxd.gluu.org/docs/plugin/wordpress/`

**Comment by willow9886** [comment]
Fixed with new linking structure.
