### ISSUE TITLE
Support refresh token for get_user_info API call

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#64]
It would be great if this could also be supported:

```
{
    "command":"get_user_info",
    "params": {
        "oxd_id":"6F9619FF-8B86-D011-B42D-00CF4FC964FF",
        "refresh_token":"SlAV32hkKG"
    }
}
```
The response should include a new access token and refresh token.

**Comment by yuriyz** [comment]
after short discussion it looks more like we need new command to get `access_token` by `refresh_token`. `refresh_token` is returned by `get-tokens-id-access-by-code`.  

https://gluu.org/docs/oxd/protocol/#get-tokens-id-access-by-code

**Comment by yuriyz** [comment]
Added new `get_access_token_by_refresh_token` command to obtain new `access_token` by `refresh_token`.

Request
```json
{
    "command":"get_access_token_by_refresh_token",
    "params": {
        "oxd_id":"6F9619FF-8B86-D011-B42D-00CF4FC964FF", <- Required
        "refresh_token":"I6IjIifX0",           <- Required, refresh_token from get_tokens_by_code command
        "scope":["openid","profile"]          <- Required
    }
}
```

**Comment by yuriyz** [comment]
done in master branch
