### ISSUE TITLE
Return Signed JWT for get_user_info

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#65]
It would be helpful to return the signed JWT in get_user_info in addition to the claims. If the JWT is encrypted, it should be decrypted first (passing an encrypted JWT wouldn't be helpful).

**Comment by duttarnab** [comment]
Get User Info will return signed jwt, if  `user_info_signed_response_alg` and `user_info_encrypted_response_alg` request parameters are set during client registration. This is already working in oxd-4.0. Hence closing this issue.
