### ISSUE TITLE
Support connections via https

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxd#67]
We currently have socket connection only, no http/https .

**Comment by yuriyz** [comment]
closing, since https translator is written by Sneh as separate project.

**Comment by willow9886** [comment]
@yuriyz can you provide a link to that project?

**Comment by yuriyz** [comment]
@willow9886 can we ask Sneh ?

**Comment by willow9886** [comment]
cc @snehaldkshah

**Comment by yuriyz** [comment]
create new repo for http translator https://github.com/GluuFederation/oxd-to-http
