### ISSUE TITLE
Support Hybrid Flow

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#69]

**Comment by yuriyz** [comment]
There is new validation command introduced:

Request
```
{
    "command":"validate",
    "params": {
        "oxd_id":"6F9619FF-8B86-D011-B42D-00CF4FC964FF", <- Required
        "code":"I6IjIifX0",                              <- Required, code from OP redirect url (see example above)
        "id_token": "af0ifjsldkjaf0ifjsldkjaf0ifjsldkjaf0ifjsldkjaf0ifjsldk",                          <- Required
        "access_token":"vdsft45dslktt"          <- Optional
    }
}
```

OK Response:
```
{
    "status":"ok"
}
```
Error Response:
```
{   
    "status":"error",
    "data":{
        "error":"invalid_id_token_bad_signature",
        "error_description":"Invalid id_token. Bad signature."    
    }
}
```

All possible error codes for oxd can be found here:
https://github.com/GluuFederation/oxd/blob/master/oxd-common/src/main/java/org/xdi/oxd/common/ErrorResponseCode.java

**Comment by yuriyz** [comment]
@willow9886 not sure I got it. Actually here I added very verbose and specific error messages. Do you think it is still not specific enough?

**Comment by willow9886** [comment]
OK nvmd. You know better than I! This is a great enhancement. Nice work, YZ.

**Comment by yuriyz** [comment]
@willow9886 right, it should reduce number of support questions for oxd.

**Comment by yuriyz** [comment]
hybrid flow support added
