### ISSUE TITLE
oxd error - RuntimeError: OxD Server Error : Unknown internal server error occurs

### ISSUE THREAD

**Issue by pradeekkaruppan** [GluuFederation/oxd#70]
Hi,

I'm getting an error when calling the oxd-ruby method 'get_tokens_by_code( code, scopes, state )' in my RoR application while trying to retrieve the access_token. 

The code is as below.
access_token = @oxd_command.get_tokens_by_code( code, scopes, state )

The error I'm getting is.
RuntimeError: OxD Server Error : Unknown internal server error occurs.

**Comment by nynymike** [comment]
please register and open an issue on https://support.gluu.org
