### ISSUE TITLE
Support security of oxd-http (enforcement, token persistence, introspection)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#75]
https://www.websequencediagrams.com/files/render?link=bq4Zc9ZrU1HHGTsf284w

**Comment by yuriyz** [comment]
done

**Comment by yuriyz** [comment]
it's possible to switch off access_token check via `"protect_commands_with_access_token": false` configuration property.

Two new commands introduced:
 - setup_client 

Request -> same as for `register_site` command
Response : https://github.com/GluuFederation/oxd/blob/master/oxd-common/src/main/java/org/xdi/oxd/common/response/SetupClientResponse.java

 - get_client_token

Request:
https://github.com/GluuFederation/oxd/blob/master/oxd-common/src/main/java/org/xdi/oxd/common/params/GetClientTokenParams.java

Response: https://github.com/GluuFederation/oxd/blob/master/oxd-common/src/main/java/org/xdi/oxd/common/response/GetClientTokenResponse.java

**Comment by jschristie** [comment]
@yuriyz, will this be added as a new page in oxd docs?

**Comment by centroxy** [comment]
@jschristie Like [oxd 3.0.1 documentation](https://gluu.org/docs/oxd/3.0.1/protocol/), these two methods  setup_client and get_client_token will be included in oxd 3.1.0 documentation . These two new methods are only in oxd 3.1.0

**Comment by yuriyz** [comment]
@jschristie those are two new commands to `Protocol` page. Make sure that all libs documentation is updated too (java, c#, php and others )

**Comment by jschristie** [comment]
@centroxy: yes i get that. These will be an enhancement in 3.1.0.

Thank you@yuriyz, will add it under [protocol](https://github.com/GluuFederation/docs-oxd-prod/blob/3.1.0/3.1.0/sources/protocol/index.md) and reference it in other docs like java, c#, php and add the params too
