### ISSUE TITLE
Could not obtain token with user credentials

### ISSUE THREAD

**Issue by sakitA** [GluuFederation/oxd#77]
Changing `use_client_authentication_for_pat` and `use_client_authentication_for_aat` to `false` on `oxd-conf.json` oxd-server try to obtain token with user credentials.  But could not complete process and throw exception. And why `UmaTokenService$obtainTokenWithUserCredentials` use fixed `state` value?

**Comment by yuriyz** [comment]
@sakitA please attach oxd-server.log file

**Comment by yuriyz** [comment]
state check is fixed https://github.com/GluuFederation/oxd/commit/588c30da02218fc3dc443c4d6d6a6cf6de21fa41

**Comment by yuriyz** [comment]
for support questions, please open ticket on support.gluu.org

**Comment by sakitA** [comment]
@yuriyz I already opened a ticket [#4041](https://support.gluu.org/other/4041/obtaintokenwithusercredentials/). And this my [oxd-server.log](https://drive.google.com/file/d/0B0k0w2ZRcqm_TkluTC1Bb3Jrcjg/view?usp=sharing)

**Comment by yuriyz** [comment]
@sakitA for this particular log I can say that your OP at `https://cyber.gluu.info` returned not `200` status which leads to failure. Please check logs of the OP.

**Comment by sakitA** [comment]
Ok I will check again

**Comment by sakitA** [comment]
@yuriyz I checked OP logs but did not find any error about this. Can you explain what is `user_id` and `user_secret` in site configuration file? If it is a user's credentials then can we think that oxd-server store last user's credentials? Or do I misunderstood whole concept?

**Comment by yuriyz** [comment]
oxd does not store user credentials. Those two properties can be read from `oxd-default-site-config.json`. There are no way to pass it with request since primary and main way is to obtain token via client authentication.

**Comment by sakitA** [comment]
@yuriyz thanks I understand my mistake now
