### ISSUE TITLE
can not register client scopes

### ISSUE THREAD

**Issue by sakitA** [GluuFederation/oxd#78]
Gluu server does not consider client scopes if it is not default on server

**Comment by yuriyz** [comment]
this is not bug, works by design. Please check docs https://gluu.org/docs/ce/3.0.1/admin-guide/openid-connect/#scopes

**Comment by sakitA** [comment]
@yuriyz I did not say that this a bug. I just say that on the documentation does not inform about this.

**Comment by yuriyz** [comment]
@sakitA  https://gluu.org/docs/ce/3.0.1/admin-guide/openid-connect/#scopes
```
Specifying a scope as "Default" means that a client can request it during dynamic client registration. The only default scope is openid, which is required by the OpenID Connect specification. You can always explicitly release a scope to a certain client later on, but this will require some manual intervention by the Gluu Server admin.
```

**Comment by sakitA** [comment]
@yuriyz thank you very much.
