### ISSUE TITLE
Defective client registration when executing register site

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxd#85]
**Problem 1:**

When using **oxd-server-3.1.0-SNAPSHOT-distribution.zip** and trying to register a site, the OIDC client is being created with the scopes *permission* and *openid* no matter what scopes are being passed in Java for registration, or those used in the json config file.

The following is an example of code used to register a client with several scopes. Attached to this issue you can see the config files as I have them

So I found no correlation of what's set in the .json files or .java with the scopes finally stored in LDAP. See attached .ldif file for an export of client created with Java code below

```
public String doRegister() throws Exception{
        try {
            client = new CommandClient("localhost", 8099);

            RegisterSiteParams cmdParams = new RegisterSiteParams();
            cmdParams.setAuthorizationRedirectUri("https://localhost:8463/cred-manager/");
            cmdParams.setPostLogoutRedirectUri("https://localhost:8463/cred-manager/bye.zul");
            cmdParams.setAcrValues(Arrays.asList("u2f","auth_ldap_server","twilio_sms"));

            //TODO: oxd bug? setting scopes...
            String[] requiredOpenIdScopes =new String[]{"openid","profile","user_name","email","mobile_phone","phone","clientinfo"};
            cmdParams.setScope(Arrays.asList(requiredOpenIdScopes));

            cmdParams.setResponseTypes(Arrays.asList("code"));  //Use "token","id_token" for implicit flow
            cmdParams.setTrustedClient(true);
            //cmdParams.setGrantType(Collections.singletonList("authorization_code"));      //this is the default grant
            cmdParams.setClientName("cred-manager");

            Command command = new Command(CommandType.REGISTER_SITE).setParamsObject(cmdParams);

            RegisterSiteResponse site = client.send(command).dataAsResponse(RegisterSiteResponse.class);
            oxdId=site.getOxdId();

            modifyExpiration(client,oxdId);
        }
        finally {
            CommandClient.closeQuietly(client);
        }
}
```

**Problem 2**

I would like to have a non-expiring client, i.e. expiration date=0, but it is not picking the date being passed. I have tried 0 or null and this creates a client expiring in 24 hours or so. However if I pass a value greater than zero, it sets the expiration acordingly in this case. 

The following is the Java code used for a one year expiration. Commented the attempts that did not work:

```
public void modifyExpiration(CommandClient client, String oxdId) throws Exception{

        UpdateSiteParams cmdParams = new UpdateSiteParams();
        cmdParams.setOxdId(oxdId);
        /*
        oxd does not let me to set indefinite expiration :(
        cmdParams.setClientSecretExpiresAt(null);
        cmdParams.setClientSecretExpiresAt(new Date(0));
        */
        GregorianCalendar cal=new GregorianCalendar();
        cal.add(Calendar.YEAR,1);
        cmdParams.setClientSecretExpiresAt(new Date(cal.getTimeInMillis()));
        logger.info(Labels.getLabel("app.extend_expiration_time"));

        Command command = new Command(CommandType.UPDATE_SITE).setParamsObject(cmdParams);
        client.send(command).dataAsResponse(UpdateSiteResponse.class);

}
```

**Problem 3**

This is minor but maybe reveals a problem. After adding manually the missing scopes in ldap, and executing a get user info, I obtain the claims...

If my user has several mobile phone numbers, so that "*mobile*" attribute is repeated several times with different values in ldap, I do not get the values separatedly in Java: I am getting them comma-separated.

Thus, if I do this:
```
claims.get("phone_mobile_number")
```
I am getting a singleton list with phone numbers in a single string. Like this ["phone1, phone2"] instead of ["phone1", "phone2"]

[oxd-config-files.txt](https://github.com/GluuFederation/oxd/files/1180577/oxd-config-files.txt)

**Comment by jgomer2001** [comment]
This is the export of client created:
[client_created.ldif.txt](https://github.com/GluuFederation/oxd/files/1180579/client_created.ldif.txt)

Here is the oxd-server log when register site takes place:
[oxd-server.log.txt](https://github.com/GluuFederation/oxd/files/1180582/oxd-server.log.txt)

**Comment by yuriyz** [comment]
Problem 1 : I run regular oxd test with scope `profile` and it is perfectly stored.
https://github.com/GluuFederation/oxd/blob/master/oxd-client/src/test/java/org/xdi/oxd/client/RegisterSiteTest.java#L34-34

**Comment by yuriyz** [comment]
@jgomer2001 looking into your logs it seems you are have op_host set to localhost, make sure appropriate scopes has "default" value set to 'true' in oxTrust otherwise it is ignore during dynamic registration which makes you think it does not work.

**Comment by yuriyz** [comment]
Problem 2 : it works by design. oxauth support only valid `java.util.Date`, under valid means in future.

**Comment by yuriyz** [comment]
Problems 3 : it's bug in oxauth already described here https://github.com/GluuFederation/oxAuth/issues/600

**Comment by jgomer2001** [comment]
@yuriyz Great
