### ISSUE TITLE
authorization_redirect_uri not being updated during  update_site_registration command

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#86]
During setup_client,  authorization_redirect_uri value was https://client.example.com:8080/userinfo
During update_site_registration, updated authorization_redirect_uri to https://client.example.com:8080
But oxd still using the previous AuthRedirectUrl (https://client.example.com:8080/userinfo) used during setup_client.
Oxd log available at  [https://pastebin.com/iHBt3yST](https://pastebin.com/iHBt3yST)

**Comment by yuriyz** [comment]
Fixed.
