### ISSUE TITLE
client_frontchannel_logout_uris  not getting Updated using oxd 'Update_Site_Registration' command 

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#88]
client_frontchannel_logout_uris  not getting Updated using oxd 'Update_Site_Registration' command 
oxd 3.1.0 version

**Comment by yuriyz** [comment]
I checked it. `front_channel_logout_uris` are updated in the requested to oxauth. If it's not persisted into ldap then it is probably `oxauth` issue. Please make sure logout uri is changed in request to `oxd`, if it is changed then please open issue on `oxauth` project to track it.
