### ISSUE TITLE
oxd 3.1.1 packaging : create package with oxd-https-extension disabled by default

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#90]
We need to create 3.1.1 oxd packages based on:

1. oxd-server https://github.com/GluuFederation/oxd/tree/version_3.1.0
2. oxd-https-extension https://github.com/GluuFederation/oxd-to-http/tree/version_3.1.0

With commands like:
```
service oxd-server start
service oxd-https-extension start
```

**Comment by adrian-gluu** [comment]
you mention something about to add redis? to which one? both pkgs needs reddis as a dependency?

**Comment by yuriyz** [comment]
@adrian-gluu I think we agreed to have one package with oxd-server and oxd-https-extention (previosly called oxd-web or oxd-to-http). And yes, correct, we need redis there. I'm adding redis support to oxd-server right now as requested by @nynymike .

**Comment by yuriyz** [comment]
cc @willow9886

**Comment by adrian-gluu** [comment]
redis just for  oxd-server or for both also oxd-https-extention

**Comment by adrian-gluu** [comment]
which branch i should use master or 3.1.0?

**Comment by yuriyz** [comment]
in description u can see two links two version_3.1.0. We need only one package with both oxd-server, oxd-http-extension and redis. All in one.

Also we need command to start/stop them.

**Comment by adrian-gluu** [comment]
ok got it both pkgs in one about braches which one i should use:
master or 3.1.0?

**Comment by yuriyz** [comment]
in the description u can see links to branches,  can u see it?

**Comment by adrian-gluu** [comment]
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-oxd-server_3.1.0-2+trusty+Ub14.04_all.deb
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/oxd-http-extension_1.2-1~trusty+Ub14.04_all.deb

redis is a dependency, just install gluu-oxd-server it will do all the magic. It will install oxd-http-extensions and redis

you need to use apt course not manually, you need to use our trusty-devel repo to fetch it

**Comment by adrian-gluu** [comment]
let re explain using the repo trusty-devel in your source list you can install one pkg and it will installl all the rest:
apt-get install gluu-oxd-server
that command it will call oxd-http-extension_1.2-1~trusty+Ub14.04_all.deb and redis-server

**Comment by yuriyz** [comment]
@adrian-gluu oxd-http-extension should be 3.1.0

**Comment by adrian-gluu** [comment]
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/oxd-http-extension_3.1.0-1~trusty+Ub14.04_all.deb

**Comment by yuriyz** [comment]
solved
