### ISSUE TITLE
UMA 2 : add custom redirect parameters to get_claims_gathering_url command

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#91]
Add custom parameters to get_claims_gathering_url command. Filter out existing client_id, state, claims_redirect_uri, ticket.

spec: https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/426
