### ISSUE TITLE
oxd-https-extension: Not properly return error response

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxd#97]
oxd-https-extension does not return the status="error"
In status= "error" situation it only returns the message `"There is no response produced by Processor. Please check oxd server logs"`

oxd-http-extension log: https://pastebin.com/T5CDj9yD
oxd-server log: https://pastebin.com/6jRGFgZZ

Error response is required at the time of claim_gatering(need_info) process

**Comment by yuriyz** [comment]
fixed
